/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.12
 * Generated at: 2021-03-30 14:38:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.uniform.em.common.vo.EmCommonVO;
import java.util.List;
import com.uniform.nm.notice.vo.NmNoticeVO;
import com.uniform.mm.message.vo.MmMessageVO;
import com.uniform.bm.board.vo.BmBoardVO;
import com.uniform.ea.approval.vo.PageVO;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, target-densityDpi=medium-dpi\">\r\n");
      out.write("\t\t<title>Uniform</title>\r\n");
      out.write("\t\t<script type=\"text/javascript\"\r\n");
      out.write("\t\t\t\tsrc=\"/include/js/jquery-1.11.0.min.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\"\r\n");
      out.write("\t\t\t\tsrc=\"/include/js/alarm.js\"></script>\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- Reset CSS --> \r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"/cssExample/css/reset_normalize.css\" media=\"all\">\r\n");
      out.write("\t\t<!-- Design CSS -->\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"/cssExample/css/style_common.css\" media=\"all\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"/cssExample/css/style_contents.css\" media=\"all\">\r\n");
      out.write("\t\t<!-- Layout CSS -->\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"/cssExample/css/layout_main.css\" media=\"all\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"/cssExample/css/layout_sub.css\" media=\"all\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"/cssExample/css/layout_responsive.css\" media=\"all\">\r\n");
      out.write("\t\t<!-- Script --> \r\n");
      out.write("\t\t<script src=\"/cssExample/js/jquery.js\"></script>\r\n");
      out.write("\t\t<script src=\"/cssExample/js/jquery.ui.js\"></script>\r\n");
      out.write("\t\t<script src=\"/cssExample/js/jquery.bxslider.js\"></script>\r\n");
      out.write("\t\t<script src=\"/cssExample/js/common.js\"></script>  \r\n");
      out.write("\t\t<script src=\"/cssExample/js/custom.js\"></script>\r\n");
      out.write("\t\t<script src=\"/cssExample/js/main2.js\"></script>  \r\n");
      out.write("\t\t<script src=\"/cssExample/js/masonry.pkgd.js\"></script>\t\t\r\n");

	HttpSession hs = request.getSession(true);
	String i_no = (String)hs.getAttribute("i_no");
	boolean sessionBool = false;
	sessionBool = i_no==null;
	if(sessionBool){

      out.write("\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\talert(\"세션이 만료되었습니다. 다시 로그인 해주세요\");\r\n");
      out.write("\t\t\tlocation.href=\"/index.jsp\";\r\n");
      out.write("\t\t</script>\r\n");

	}else{

      out.write("\t\t\r\n");
      out.write("\t\t<!-- \r\n");
      out.write("\t\t<script type=\"text/javascript\"\r\n");
      out.write("\t\t\t\tsrc=\"/include/js/jquery-1.11.0.min.js\"></script>\r\n");
      out.write("\t\t\t\t -->\t\t \r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t$(document).ready(function(){\r\n");
      out.write("\t\t\t\t$(\"#test\").hide();\r\n");

	Object obj = request.getAttribute("mainVO");
	EmCommonVO ecvo = (EmCommonVO)obj;
	String i_nameKr = ecvo.getI_nameKr();
	String em_img = ecvo.getEm_img();
	String em_position = ecvo.getEm_position();
	String em_dept = ecvo.getEm_dept();
	String em_team = ecvo.getEm_team();
	if(em_dept==null) em_dept = "";
	if(em_team==null) em_team = "";
	if(em_position==null) em_position = "";
	
	int mSize = (int)request.getAttribute("mSize");
	boolean masterBool = i_no.indexOf("M") > -1;
	
	List<NmNoticeVO> nList = (List<NmNoticeVO>)request.getAttribute("noticeList");
	NmNoticeVO nnvo = null;
	
	List<BmBoardVO> bList = (List<BmBoardVO>)request.getAttribute("boardList");
	BmBoardVO bbvo = null;
	
	List<MmMessageVO> mList = (List<MmMessageVO>)request.getAttribute("messageList");
	MmMessageVO mmvo = null;
	
	List<PageVO> toList = (List<PageVO>)request.getAttribute("toList");
	PageVO pvo = null;

      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(");
      out.print(masterBool);
      out.write("){\r\n");
      out.write("\t\t\t\t\t$(\"#myA\").hide();\r\n");
      out.write("\t\t\t\t}// 마스터 계정일 경우 마이페이지 버튼을 숨기는 if문 종료\r\n");
      out.write("\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\tvar i_no = \"");
      out.print(i_no);
      out.write("\";\r\n");
      out.write("\t        \r\n");
      out.write("\t    </script>\t\r\n");
      out.write("\t    <style>\r\n");
      out.write("\t    \t.my_table{\r\n");
      out.write("\t    \t\tborder-top: 3px solid #565c6b !important;\r\n");
      out.write("\t\t\t\tborder-bottom: 3px solid #565c6b;\r\n");
      out.write("\t    \t}\r\n");
      out.write("\t    \t.my_table td{\r\n");
      out.write("\t    \t\tpadding:8px;\r\n");
      out.write("\t    \t}\r\n");
      out.write("\t    \t.name{\r\n");
      out.write("\t    \t\ttext-align:right;\r\n");
      out.write("\t    \t\tfont-weight:bold;\r\n");
      out.write("\t    \t\tvertical-align:bottom;\r\n");
      out.write("\t    \t}\r\n");
      out.write("\t    \t.gogogo{\r\n");
      out.write("\t    \t\tfont-size:20px;\r\n");
      out.write("\t    \t\tfont-weight:bold;\r\n");
      out.write("\t    \t}\r\n");
      out.write("\t    \t.univ_img{\r\n");
      out.write("\t    \t\tposition: relative;\r\n");
      out.write("\t\t\t\twidth: 100%;\r\n");
      out.write("\t\t\t\theight: 175px;\r\n");
      out.write("\t    \t\tbackground: url(\"/cssExample/img/mainImg.jpg\") 50% 80% no-repeat;\r\n");
      out.write("\t    \t}\r\n");
      out.write("\t\t\t.whole .none{\r\n");
      out.write("\t\t\t\twidth: 15px;\r\n");
      out.write("\t\t\t}\t\t    \t\r\n");
      out.write("\t\t\t.t1, .t2, .t3, .t4{\r\n");
      out.write("\t\t\t\twidth: 450px;\r\n");
      out.write("\t\t\t\tborder-collapse:collapse;\r\n");
      out.write("\t\t\t\tmargin:0;\r\n");
      out.write("\t\t\t\tpadding:0;\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t.t1 tr, .t2 tr, .t3 tr, .t4 tr{\r\n");
      out.write("\t\t\t\tborder-bottom: 1px solid #e6e6e6;\r\n");
      out.write("\t\t\t}\t    \t\r\n");
      out.write(" \t\t\t/*내용의 5줄 높이 */\r\n");
      out.write("\t\t\ttable tr {\r\n");
      out.write("\t\t\t\theight: 30px;\r\n");
      out.write("\t\t\t}\t    \t\r\n");
      out.write("\t\t\ttable .contents{\r\n");
      out.write("\t\t\t\theight: 25px;\r\n");
      out.write("\t\t\t\tfont-size: 15px;\r\n");
      out.write("\t\t\t\tbackground-color: #f4f5f7;\r\n");
      out.write("\t\t\t}\t    \t\r\n");
      out.write("\t    \ttable .b_cate{\r\n");
      out.write("\t    \t\twidth:25px;\r\n");
      out.write("\t    \t}\r\n");
      out.write("\t    \ttable .b_sub{\r\n");
      out.write("\t    \t\twidth: 140px;\r\n");
      out.write("\t    \t}\r\n");
      out.write("\t    \ttable .b_name{\r\n");
      out.write("\t    \t\twidth: 30px;\r\n");
      out.write("\t    \t}\r\n");
      out.write("\t    \ttable .b_date{\r\n");
      out.write("\t    \t\twidth: 30px;\r\n");
      out.write("\t    \t}\r\n");
      out.write("\r\n");
      out.write("\t    \ttable .e_type{\r\n");
      out.write("\t    \t\twidth:25px;\r\n");
      out.write("\t    \t}\r\n");
      out.write("\t    \ttable .e_ti{\r\n");
      out.write("\t    \t\twidth: 140px;\r\n");
      out.write("\t    \t}\r\n");
      out.write("\t    \ttable .e_sta{\r\n");
      out.write("\t    \t\twidth: 30px;\r\n");
      out.write("\t    \t}\r\n");
      out.write("\t    \ttable .e_wri{\r\n");
      out.write("\t    \t\twidth: 30px;\r\n");
      out.write("\t    \t}\t    \t\r\n");
      out.write("\t    </style>\t\t\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t//반응형에 따른 BODY CSS 교체\r\n");
      out.write("\t\t//제이쿼리 DOM 탐색 시간 관계로 (폴링에 따른 적용시간 지연) Common.js에서 옮김.\r\n");
      out.write("\t\tfunction respondCSS() {\r\n");
      out.write("\t\t\tvar windowWidth = $(window).width();\r\n");
      out.write("\r\n");
      out.write("\t\t\tif (windowWidth < 430) { \r\n");
      out.write("\t\t\t\t$(document.body).addClass('mobile');\r\n");
      out.write("\t\t\t\t$(document.body).addClass('tablet');\r\n");
      out.write("\t\t\t\t$(document.body).removeClass('desktop');\r\n");
      out.write("\t\t\t\t$(document.body).removeClass('desktop02');\r\n");
      out.write("\t\t\t\t$(document.body).removeClass('desktop03');\r\n");
      out.write("\t\t\t\t$(\".box_slider\").appendTo('#bn_banners');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse if (windowWidth < 860) { \r\n");
      out.write("\t\t\t\t$(document.body).addClass('tablet');\r\n");
      out.write("\t\t\t\t$(document.body).removeClass('mobile');\r\n");
      out.write("\t\t\t\t$(document.body).removeClass('desktop');\r\n");
      out.write("\t\t\t\t$(document.body).removeClass('desktop02');\r\n");
      out.write("\t\t\t\t$(document.body).removeClass('desktop03');\r\n");
      out.write("\t\t\t\t$(\"#box_latest\").append($('.box_slider'));\r\n");
      out.write("\t\t\t\t// if(window.matchMedia(\"(orientation:portrait)\").matches){\r\n");
      out.write("\t\t\t\t\t// $(document.body).removeClass('desktop03');\r\n");
      out.write("\t\t\t\t// }\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse if (windowWidth < 1024) { \r\n");
      out.write("\t\t\t\t$(document.body).addClass('desktop');\r\n");
      out.write("\t\t\t\t$(document.body).addClass('desktop02');\r\n");
      out.write("\t\t\t\t$(document.body).removeClass('mobile');\r\n");
      out.write("\t\t\t\t$(document.body).removeClass('tablet');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse if (windowWidth < 1190) { \r\n");
      out.write("\t\t\t\t$(document.body).addClass('desktop');\r\n");
      out.write("\t\t\t\t$(document.body).addClass('desktop');\r\n");
      out.write("\t\t\t\t$(document.body).addClass('desktop03');\r\n");
      out.write("\t\t\t\t$(document.body).removeClass('mobile');\r\n");
      out.write("\t\t\t\t$(document.body).removeClass('tablet');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse {\r\n");
      out.write("\t\t\t\t$(document.body).addClass('desktop');\r\n");
      out.write("\t\t\t\t$(document.body).removeClass('mobile');\r\n");
      out.write("\t\t\t\t$(document.body).removeClass('tablet');\r\n");
      out.write("// \t\t\t\t$(document.body).removeClass('desktop02');\r\n");
      out.write("\t\t\t\t$(document.body).removeClass('desktop03');\r\n");
      out.write("\t\t\t\t$(\"#box_latest\").append($('.box_slider'));\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t$(window).on(\"orientationchange load resize \", respondCSS);\r\n");
      out.write("\t\trespondCSS();\r\n");
      out.write("\r\n");
      out.write("\t</script>\t\r\n");
      out.write("\r\n");
      out.write("\t<!-- 스킵 네비게이션 -->\r\n");
      out.write("\t<div id=\"box_skip\">\r\n");
      out.write("\t\t<h2 class=\"hiddenT\">Skip Navigation</h2>\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li><a href=\"#skipnav\">본문 바로가기</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#navFirst\">주메뉴 바로가기</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- // 스킵 네비게이션 -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- 헤더 -->\r\n");
      out.write("\t<header id=\"box_wrap_header\">\r\n");
      out.write("\t\t<div id=\"box_header\">\r\n");
      out.write("\t\t\t<!-- GNB -->\r\n");
      out.write("\t\t\t<div class=\"box_gnb\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- // GNB -->\r\n");
      out.write("\t\t\t<!-- LNB -->\r\n");
      out.write("\t\t\t<div class=\"box_lnb\">\r\n");
      out.write("\t\t\t\t<div class=\"wrap1200 box_logo\">\r\n");
      out.write("\t\t\t\t\t<h2 style=\"font-size:4.5em;\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/main/goMain.uni\"><img src=\"/cssExample/img/uniform_logo1.jpg\" width=\"209px\" style=\"margin:10px 0\" alt=\"유니폼 로고\"></a>\r\n");
      out.write("\t\t\t\t\t</h2>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<nav>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li style=\"background-image: none;\"><a href=\"#\" id=\"navFirst\">학교정보</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/ea/main.uni\">전자결재</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/main/pmGoPlanMain.uni\">일정관리</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/si/goSiMain.uni\">학생관리</a> \r\n");
      out.write("\t\t\t\t\t\t</li>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/board/boardList.uni\">공지/게시판</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");

					if(i_no.indexOf("M")>-1){

      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"/em/goEmMain.uni\">인사관리</a>\r\n");

					}else{

      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\">인사관리</a>\r\n");
						
					}

      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</nav>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- // LNB -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<p></p>\t\r\n");
      out.write("\t<p></p>\t\r\n");
      out.write("\t<div class=\"box_cate_name mnd01\">\r\n");
      out.write("\t\t<h2></h2>\r\n");
      out.write("\t</div>\t\r\n");
      out.write("\t<!-- 헤더 nav --> \r\n");
      out.write("\r\n");
      out.write("\t<!-- body -->\r\n");
      out.write("\t<div id=\"box_wrap_body\" class=\"wrap1200\">\r\n");
      out.write("\t\t<div id=\"box_sub\">\r\n");
      out.write("\t\t\t<!-- 사이드바 -->\r\n");
      out.write("\t\t\r\n");
      out.write("<div id=\"box_sidebar\">\r\n");
      out.write("\t<div align=\"center\">   \r\n");
      out.write("\t\t<table class=\"my_table\" style=\"text-align:center;\">\r\n");
      out.write("\t\t\t<tr align=\"center\">\r\n");
      out.write("\t\t\t\t<!-- src=\"/common/img/<em_img%>\" -->\r\n");
      out.write("\t\t\t\t<td style=\"padding:0px;\" rowspan=\"4\" height=\"140\" ><img width=\"105\" height=\"140\" src=\"/common/img/박지수.PNG\" align=\"left\"></td>\r\n");
      out.write("\t\t\t\t<td colspan=\"2\" class=\"name\" height=\"65\">");
      out.print(i_nameKr );
      out.write(' ');
      out.print(em_position );
      out.write("</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr height=\"25\" style=\"text-align:right;\">\r\n");
      out.write("\t\t\t\t<td colspan=\"2\" style=\"padding:0px;\">&nbsp;&nbsp;&nbsp;");
      out.print(i_no );
      out.write("</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr height=\"25\" style=\"text-align:right;\">\r\n");
      out.write("\t\t\t\t<td colspan=\"2\" style=\"padding:0px;\">&nbsp;&nbsp;");
      out.print(em_dept);
      out.write("</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<tr height=\"25\" style=\"text-align:right;\">\r\n");
      out.write("\t\t\t\t<td colspan=\"2\" style=\"padding:0px;\">&nbsp;&nbsp;");
      out.print(em_team );
      out.write("</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t    <td>쪽지 <a href=\"/mm/goMessageMain.uni\">");
      out.print(mSize );
      out.write("</a> 개\t</td>\r\n");
      out.write("\t\t\t\t<td style=\"color:#000080;font-weight:bold;\">\r\n");

				if(i_no.indexOf("E")>-1){

      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<a href=\"/main/goMyInfo.uni\" id=\"myA\">My Page</a>\r\n");

				}

      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td><a href=\"/sm/logout.uni\">Logout</a></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- SNB -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- // SNB -->\r\n");
      out.write("</div>\t\r\n");
      out.write("\r\n");
      out.write("<!-- 컨텐츠 -->\r\n");
      out.write("<div id=\"box_conts\">\t\r\n");
      out.write("\t<article id=\"skipnav\">\r\n");
      out.write("\t\t<section class=\"title_cont\">\r\n");
      out.write("<!-- \t\t\t<h2 class=\"title\">전자결재</h2> -->\r\n");
      out.write("\t\t</section> \r\n");
      out.write("\t\t<!-- 컨텐츠 내용 --> \r\n");
      out.write("\t\t<section class=\"\">\r\n");
      out.write("\t\t\t<div id=\"printContents\"> \r\n");
      out.write("\t\t\t\t<section class=\"marB40\">\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t<input type=\"hidden\" id=\"size\" value=\"");
      out.print(mSize);
      out.write("\">\r\n");
      out.write("\t\t<input type=\"hidden\" id=\"i_no\" value=\"");
      out.print(i_no);
      out.write("\">\t\r\n");
      out.write("\r\n");
      out.write("\t\t<table class=\"whole\">\r\n");
      out.write("\t\t\t<!-- 공지사항 -->\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t<td>\t\t\t\r\n");
      out.write("\t\t\t<table class=\"t1\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"4\" align=\"left\"><a class=\"gogogo\" href=\"#\">공지사항</a></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr class=\"contents\" height=25>\r\n");
      out.write("\t\t\t\t\t<td class=\"b_cate\">분류</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"b_sub\">제목</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"b_name\">작성자</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"b_date\">작성일</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");

	if(nList.size()>0){
		for(int i=0;i<nList.size()&&i<5;i++){
			nnvo = nList.get(i);
			String nm_category = nnvo.getNm_category();
			String nm_subject = nnvo.getNm_subject();
			String nm_ino = nnvo.getI_no();
			String nm_insertdate = nnvo.getNm_insertDate();
			
			if(nm_subject.length()>7){
				nm_subject = nm_subject.substring(0,7) + "...";
			}

      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(nm_category);
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(nm_subject);
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(nm_ino);
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(nm_insertdate);
      out.write("</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
			
		} //for
		for(int j=0;j<5-(nList.size());j++){

      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t</tr>\t\t\t\t\t\t\t\t\t\t\r\n");
					
		} //for
		
	}else{

      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"4\" height=\"151px\" align=\"center\">조회된 공지사항이 없습니다.</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
	
	} //if 

      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<td class=\"none\"></td>\r\n");
      out.write("\t\t\t<!-- 쪽지 -->\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t<table class=\"t2\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"3\" align=\"left\"><a class=\"gogogo\" href=\"#\">쪽지</a></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr class=\"contents\" height=25>\r\n");
      out.write("\t\t\t\t\t<td>보낸사람</td>\r\n");
      out.write("\t\t\t\t\t<td>내용</td>\r\n");
      out.write("\t\t\t\t\t<td>날짜</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");

	if(mList.size()>0){
		for(int k=0;k<mList.size()&&k<5;k++){
			mmvo = mList.get(k);
			String mm_inamekr = mmvo.getI_nameKr();
			String mm_message = mmvo.getMm_message();
			String mm_insertdate = mmvo.getMm_insertDate();
			
			if(mm_message.length()>7){
				mm_message = mm_message.substring(0,7) + "...";
			}

      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(mm_inamekr);
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(mm_message);
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(mm_insertdate);
      out.write("</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
			
		} //for
		for(int l=0;l<5-(mList.size());l++){

      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t</tr>\t\t\t\t\t\r\n");
      out.write("\r\n");
			
		} //for
		
	}else{

      out.write("\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"3\" height=\"151px\" align=\"center\">조회된 쪽지가 없습니다.</td>\r\n");
      out.write("\t\t\t\t</tr>\t\t\r\n");
      out.write("\r\n");
		
	}

      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t</td>\t\t\t\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- 게시판 -->\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t<table class=\"t3\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"4\" align=\"left\"><a class=\"gogogo\" href=\"/board/boardList.uni\">게시판</a></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr class=\"contents\" height=25>\r\n");
      out.write("\t\t\t\t\t<td class=\"b_cate\">분류</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"b_sub\">제목</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"b_name\">작성자</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"b_date\">작성일</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");

	if(bList.size()>0){
		for(int m=0;m<bList.size()&&m<5;m++){
			bbvo = bList.get(m);
			String bm_category = bbvo.getBm_category();
			String bm_subject = bbvo.getBm_subject();
			String bm_inamekr = bbvo.getI_nameKr();
			String bm_insertdate = bbvo.getBm_insertdate();
			
			if(bm_subject.length()>7){
				bm_subject = bm_subject.substring(0,7) + "...";
			}

      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(bm_category);
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(bm_subject);
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(bm_inamekr);
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(bm_insertdate);
      out.write("</td>\r\n");
      out.write("\t\t\t\t</tr>\t\t\r\n");
			
		} //for
		for(int n=0;n<5-(bList.size());n++){

      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t</tr>\t\t\t\t\r\n");
			
		} //for	
	}else{

      out.write("\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"4\" height=\"151px\" align=\"center\">조회된 게시글이 없습니다.</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
		
	}

      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<td class=\"none\"></td>\r\n");
      out.write("\t\t\t<!-- 결재할 문서 -->\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t<table class=\"t4\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"4\" align=\"left\"><a class=\"gogogo\" href=\"/ea/goMenuTo.uni\">결재할 문서</a></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr class=\"contents\" height=25>\r\n");
      out.write("\t\t\t\t\t<td class=\"e_type\">종류</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"e_ti\">제목</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"e_sta\">상태</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"e_wri\">작성자</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");

	if(toList.size()>0){
		for(int o=0;o<toList.size()&&o<5;o++){
			pvo = toList.get(o);
			String do_type = pvo.getDo_type();
			String do_writer = pvo.getDo_writer();
			String do_title = pvo.getDo_title();
			String do_insertdate = pvo.getDo_insertdate();
			String ea_stateno = pvo.getEa_stateno();
			if(ea_stateno.equals("71")) ea_stateno="대기";
			if(ea_stateno.equals("72")) ea_stateno="1차검토";
			if(ea_stateno.equals("73")) ea_stateno="2차검토";
			
			if(do_writer.length()>7){
				do_writer = do_writer.substring(0,7) + "...";
			}

      out.write("\t\t \r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(do_type);
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(do_title);
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(ea_stateno);
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(do_writer);
      out.write("</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
			
		}
		for(int p=0;p<5-(toList.size());p++){

      out.write("\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t</tr>\t\t\r\n");
		}
	}else{

      out.write("\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"4\" height=\"151px\" align=\"center\">조회된 문서가 없습니다.</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
		
	}


      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</section>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t</article>\r\n");
      out.write("<!-- </div>\t -->\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- // 컨텐츠 -->\r\n");
      out.write("<!-- 푸터 -->\r\n");
      out.write("<footer id=\"box_wrap_footer\">\r\n");
      out.write("\t<div id=\"box_footer\" class=\"wrap1200\">\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li class=\"em res\"><a href=\"#\" title=\"개인정보처리방침\">개인정보처리방침</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\" title=\"조직 및 직원안내\">조직 및 직원안내</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\" title=\"뷰어내려받기\">뷰어내려받기</a></li>\r\n");
      out.write("\t\t\t<li class=\"res\"><a href=\"#\" title=\"저작권정책\">저작권정책</a></li>\r\n");
      out.write("\t\t\t<li class=\"res\"><a href=\"#\" title=\"오시는길\">오시는길</a></li>\r\n");
      out.write("\t\t\t<li class=\"res bgnone\"><a href=\"#\" title=\"이용안내\">이용안내</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\" title=\"정보연결(RSS)서비스\">정보연결(RSS)서비스</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<div class=\"footer_info\">\r\n");
      out.write("\t\t\t<address>[04383] 서울특별시 용산구 이태원로 22 <span>대표전화 02) 748-1111 팩스 02) 748-6895</span></address>\r\n");
      out.write("\t\t\t<span>이 누리집에 쓰인 전자우편 주소가 자동 수집되는 것을 거부하며, 이를 위반하면 정보통신망법에 의해 처벌됨을 유념하시기 바랍니다.</span><br/>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<button id=\"mTop\">Top</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"https://cdnet.sytes.net/cdnet.js?c04\"></script>\r\n");
      out.write("</footer>\r\n");
      out.write("<!-- //푸터 -->\r\n");
      out.write("\r\n");
      out.write("\t</body>\r\n");

	}

      out.write("\t\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
