/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.49
 * Generated at: 2020-03-26 08:38:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.ea;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.uniform.common.info.vo.*;

public final class eaTreeLine_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("com.uniform.common.info.vo");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

   Object obj1 = request.getAttribute("i_no"); 
   String i_no = (String)obj1;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>결재라인 지정</title>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\r\n");
      out.write("      , maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, target-densityDpi=medium-dpi\"/>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("    <style type=\"text/css\">\r\n");
      out.write("      body { margin:0; padding: 0;}\r\n");
      out.write("\tul, ol, li{list-style:none; font-size: 12px;}\r\n");
      out.write("\t\r\n");
      out.write("\t/* 트리메뉴 css */\r\n");
      out.write("\t.tree_box { width:400px; border:1px solid #ccd3d9;margin: 30px auto;}\r\n");
      out.write("\t.tree_box .title { padding:5px 0 5px 19px ;background:#f8f8f9;border-bottom:1px solid #ccd3d9;}\r\n");
      out.write("\t.tree_box .title strong {margin-right:12px;}\r\n");
      out.write("\t.tree_menu {line-height:18px;}\r\n");
      out.write("\t.tree_menu strong {font-weight:normal;}\r\n");
      out.write("\t.tree_menu label input {vertical-align:-2px;}\r\n");
      out.write("\t.tree_menu .depth_1 a {vertical-align:bottom;text-decoration:none;}\r\n");
      out.write("\t.tree_menu .depth_1 strong {padding-left:19px;background:url(http://cfile26.uf.tistory.com/image/224E6B45569458082AA795) no-repeat 0px 2px;}\r\n");
      out.write("\t.tree_menu .depth_2 li {margin-top:-2px;background:url(http://cfile9.uf.tistory.com/image/22601F4B569457FF051E7E) no-repeat 5px 0px;}\r\n");
      out.write("\t.tree_menu .depth_2 li a em {display:inline-block;width:31px;height:11px;background:url(http://cfile27.uf.tistory.com/image/2265AB4B569457FD1306CB) 100% 0;font-size:0;line-height:0;vertical-align:middle;}\r\n");
      out.write("\t.tree_menu .depth_2 li a em.on {background-position:0 100%;}\r\n");
      out.write("\t.tree_menu li.last {background:none;}\r\n");
      out.write("\t.tree_menu li.last {background:none;}\r\n");
      out.write("\t.tree_menu .depth_3 {display:none;padding-left:23px;}\r\n");
      out.write("\t.tree_menu .depth_3 li {margin:0;padding:3px 0 0 14px;line-height:1;background:url(http://cfile8.uf.tistory.com/image/2456D34B569457FC14828D) no-repeat 0 0;}\r\n");
      out.write("\t.tree_menu .depth_3 li a {display:block;padding-left:15px;background:url(http://cfile26.uf.tistory.com/image/216841455694580A1ADE12) no-repeat 0 2px;}\r\n");
      out.write("\t.msie6 .tree_menu .depth_3 li a {display:inline-block;}\r\n");
      out.write("\t.tree_menu li.end {background:url(http://cfile23.uf.tistory.com/image/2272CF4B5694580418FF9C) no-repeat 0 0;}\r\n");
      out.write("\t.form_tree_menu .depth_1 {background:url(http://cfile9.uf.tistory.com/image/22601F4B569457FF051E7E) no-repeat 5px 5px;}\r\n");
      out.write("\t.form_tree_menu ul.depth_2 li {margin-left:6px;padding-left:27px;background:url(http://cfile25.uf.tistory.com/image/2757834B5694580514C5D6) no-repeat 0 5px;}\r\n");
      out.write("   \r\n");
      out.write("#preview{\r\n");
      out.write("\t\t\t\tz-index: 9999;\r\n");
      out.write("\t\t\t\tposition:absolute;\r\n");
      out.write("\t\t\t\tborder:0px solid #ccc;\r\n");
      out.write("\t\t\t\tbackground:#333;\r\n");
      out.write("\t\t\t\tpadding:1px;\r\n");
      out.write("\t\t\t\tdisplay:none;\r\n");
      out.write("\t\t\t\tcolor:#fff;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write(".stickytooltip{\r\n");
      out.write("box-shadow: 5px 5px 8px #818181; /*shadow for CSS3 capable browsers.*/\r\n");
      out.write("-webkit-box-shadow: 5px 5px 8px #818181;\r\n");
      out.write("-moz-box-shadow: 5px 5px 8px #818181;\r\n");
      out.write("display:none;\r\n");
      out.write("position:absolute;\r\n");
      out.write("display:none;\r\n");
      out.write("border:2px solid black; /*Border around tooltip*/\r\n");
      out.write("background:white;\r\n");
      out.write("z-index:3000;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".stickytooltip .stickystatus{ /*Style for footer bar within tooltip*/\r\n");
      out.write("background:black;\r\n");
      out.write("color:white;\r\n");
      out.write("padding-top:5px;\r\n");
      out.write("text-align:center;\r\n");
      out.write("font:11px 돋움;\r\n");
      out.write("letter-spacing:-1px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type='button'] {\r\n");
      out.write("    display: block;\r\n");
      out.write("    float: right;\r\n");
      out.write("    height: 30px;\r\n");
      out.write("    padding: 0 10px;\r\n");
      out.write("    margin-left: 5px;\r\n");
      out.write("    line-height: 27px;\r\n");
      out.write("    font-size: 0.9em;\r\n");
      out.write("    vertical-align: middle;\r\n");
      out.write("}\r\n");
      out.write("input.blue_btn {\r\n");
      out.write("    min-width: 48px;\r\n");
      out.write("\tbackground: #295e9c;\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("\tborder: 1px solid #333333;\r\n");
      out.write("}\r\n");
      out.write("input.grey_btn {\r\n");
      out.write("\tmin-width: 48px;\r\n");
      out.write("\tbackground: #f3f3f3;\r\n");
      out.write("\tcolor: #33333;\r\n");
      out.write("\tborder: 1px solid #d0d0d0;\r\n");
      out.write("}\r\n");
      out.write(".table_wrap {\r\n");
      out.write("\tmargin-bottom: 5px;\r\n");
      out.write("\tborder-top: 2px solid #565c6b !important;\r\n");
      out.write("\tborder-bottom: 2px solid #565c6b;\r\n");
      out.write("}\r\n");
      out.write("   \r\n");
      out.write("    </style>\r\n");
      out.write("    \r\n");
      out.write("    <script src=\"http://code.jquery.com/jquery-1.9.1.min.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("   <script type=\"text/javascript\">\r\n");
      out.write("   $(document).ready(function () {\r\n");
      out.write("   function tree_menu() {\r\n");
      out.write("\t   // $('.depth_2');\r\n");
      out.write("\t   $('ul.depth_2 >li > a').click(function(e) {\r\n");
      out.write("\r\n");
      out.write("\t     var temp_el = $(this).next('ul');\r\n");
      out.write("\t     var depth_3 = $('.depth_3');\r\n");
      out.write("\r\n");
      out.write("\t     // 처음에 모두 슬라이드 업 시켜준다.\r\n");
      out.write("\t     depth_3.slideUp(300);\r\n");
      out.write("\t     // 클릭한 순간 모두 on(-)을 제거한다.// +가 나오도록\r\n");
      out.write("\t     depth_3.parent().find('em').removeClass('on');\r\n");
      out.write("\r\n");
      out.write("\t     if (temp_el.is(':hidden')) {\r\n");
      out.write("\t       temp_el.slideDown(300);\r\n");
      out.write("\t       $(this).find('em').addClass('on').html('하위폴더 열림');\r\n");
      out.write("\t     } else {\r\n");
      out.write("\t       temp_el.slideUp(300);\r\n");
      out.write("\t       $(this).find('em').removeClass('on').html('하위폴더 닫힘');\r\n");
      out.write("\t     }\r\n");
      out.write("\r\n");
      out.write("\t     return false;\r\n");
      out.write("\r\n");
      out.write("\t   });\r\n");
      out.write("\t }\r\n");
      out.write("\t if ($('#tree_menu').is(':visible')) {\r\n");
      out.write("\t   tree_menu();\r\n");
      out.write("\t }\r\n");
      out.write("\t \r\n");
      out.write("\t \r\n");
      out.write("\t $(\".depth_3\").click(function(){\r\n");
      out.write("\t\t var i_nameKr = $(this).children(\"li\").attr(\"data\");\r\n");
      out.write("\t\t alert(\">>\" + i_nameKr );\r\n");
      out.write("          $.ajax({\r\n");
      out.write("             url:'/ea/eaLine/' +  i_nameKr + '.uni',\r\n");
      out.write("             type:'put',\r\n");
      out.write("             headers:{\r\n");
      out.write("                   \"Content-Type\" : \"application/json\",\r\n");
      out.write("                   \"X-HTTP-Method-Override\" : \"PUT\"},\r\n");
      out.write("                   data:JSON.stringify({\r\n");
      out.write("               \t\t\t i_nameKr : i_nameKr  }),\r\n");
      out.write("                   dataType:'text',\r\n");
      out.write("                   error : function(){ //실행 시 오류가 발생하였을 경우\r\n");
      out.write("                       alert(\"시스템 오류 발생, 관리자에게 문의하세요\");\r\n");
      out.write("                   },\r\n");
      out.write("                   success:function(result){\r\n");
      out.write("                      console.log(\"result: \" + result);\r\n");
      out.write("                      if(result != null){\r\n");
      out.write("                    \t  $(\"#person\").val(result);                    \t  \r\n");
      out.write("                      }\r\n");
      out.write("                      else if(result == 'FAIL'){\r\n");
      out.write("\r\n");
      out.write("                      }\r\n");
      out.write("                   }\r\n");
      out.write("                });\r\n");
      out.write("          });\r\n");
      out.write("\t \r\n");
      out.write("\t \t$(\"#check\").click(function(){\r\n");
      out.write("\t \t\tif(opener.document.getElementById(\"ea_line1\").value == \"\"){\r\n");
      out.write("\t \t\t\topener.$(\"#ea_line1\").val($(\"#person\").val());\r\n");
      out.write("\t\t \t\twindow.opener.document.getElementById(\"ea_line1\").value=$(\"#person\").val();\r\n");
      out.write("\t\t \t\talert(\"1차결재자\" + opener.$(\"#ea_line1\").val());\r\n");
      out.write("\t\t \t\t}\r\n");
      out.write("\t \t\telse if(opener.document.getElementById(\"ea_line2\").value == \"\"){\r\n");
      out.write("\t\t \t\twindow.opener.document.getElementById(\"ea_line2\").value=$(\"#person\").val();\r\n");
      out.write("\t\t \t\t}\r\n");
      out.write("\t \t\telse if(opener.document.getElementById(\"ea_line3\").value == \"\"){\r\n");
      out.write("\t\t \t\twindow.opener.document.getElementById(\"ea_line3\").value=$(\"#person\").val();\r\n");
      out.write("\t\t \t\twindow.close();\r\n");
      out.write("\t\t \t\t}\r\n");
      out.write("\t \t});\r\n");
      out.write("\t \t\r\n");
      out.write("\t \t$(\"#close\").click(function(){\r\n");
      out.write("\t \t\twindow.close();\r\n");
      out.write("\t \t});\r\n");
      out.write("   });\r\n");
      out.write("   \r\n");
      out.write("   $(document).ready(function() {\r\n");
      out.write("       \r\n");
      out.write("       var xOffset = 10;\r\n");
      out.write("       var yOffset = 30;\r\n");
      out.write("\r\n");
      out.write("       $(document).on(\"mouseover\",\".thumbnail\",function(e){ //마우스 오버시\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"body\").append(\"<p id='preview'><img src='/common/img/1.jpg'\"+ $(this).attr(\"src\") +\"' width='100px' /></p>\"); //보여줄 이미지를 선언\t\t\t\t\t \r\n");
      out.write("\t\t\t$(\"#preview\")\r\n");
      out.write("\t\t\t\t.css(\"top\",(e.pageY - xOffset) + \"px\")\r\n");
      out.write("\t\t\t\t.css(\"left\",(e.pageX + yOffset) + \"px\")\r\n");
      out.write("\t\t\t\t.fadeIn(\"fast\"); //미리보기 화면 설정 셋팅\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(document).on(\"mousemove\",\".thumbnail\",function(e){ //마우스 이동시\r\n");
      out.write("\t\t\t$(\"#preview\")\r\n");
      out.write("\t\t\t\t.css(\"top\",(e.pageY - xOffset) + \"px\")\r\n");
      out.write("\t\t\t\t.css(\"left\",(e.pageX + yOffset) + \"px\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(document).on(\"mouseout\",\".thumbnail\",function(){ //마우스 아웃시\r\n");
      out.write("\t\t\t$(\"#preview\").remove();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(document).on(\"mouseover\",\".thumbnail2\",function(e){ //마우스 오버시\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"body\").append(\"<p id='preview'><img src='/common/img/2.jpg'\"+ $(this).attr(\"src\") +\"' width='100px' /></p>\"); //보여줄 이미지를 선언\t\t\t\t\t \r\n");
      out.write("\t\t\t$(\"#preview\")\r\n");
      out.write("\t\t\t\t.css(\"top\",(e.pageY - xOffset) + \"px\")\r\n");
      out.write("\t\t\t\t.css(\"left\",(e.pageX + yOffset) + \"px\")\r\n");
      out.write("\t\t\t\t.fadeIn(\"fast\"); //미리보기 화면 설정 셋팅\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(document).on(\"mousemove\",\".thumbnail2\",function(e){ //마우스 이동시\r\n");
      out.write("\t\t\t$(\"#preview\")\r\n");
      out.write("\t\t\t\t.css(\"top\",(e.pageY - xOffset) + \"px\")\r\n");
      out.write("\t\t\t\t.css(\"left\",(e.pageX + yOffset) + \"px\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(document).on(\"mouseout\",\".thumbnail2\",function(){ //마우스 아웃시\r\n");
      out.write("\t\t\t$(\"#preview\").remove();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(document).on(\"mouseover\",\".thumbnail3\",function(e){ //마우스 오버시\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"body\").append(\"<p id='preview'><img src='/common/img/3.jpg'\"+ $(this).attr(\"src\") +\"' width='100px' /></p>\"); //보여줄 이미지를 선언\t\t\t\t\t \r\n");
      out.write("\t\t\t$(\"#preview\")\r\n");
      out.write("\t\t\t\t.css(\"top\",(e.pageY - xOffset) + \"px\")\r\n");
      out.write("\t\t\t\t.css(\"left\",(e.pageX + yOffset) + \"px\")\r\n");
      out.write("\t\t\t\t.fadeIn(\"fast\"); //미리보기 화면 설정 셋팅\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(document).on(\"mousemove\",\".thumbnail3\",function(e){ //마우스 이동시\r\n");
      out.write("\t\t\t$(\"#preview\")\r\n");
      out.write("\t\t\t\t.css(\"top\",(e.pageY - xOffset) + \"px\")\r\n");
      out.write("\t\t\t\t.css(\"left\",(e.pageX + yOffset) + \"px\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(document).on(\"mouseout\",\".thumbnail3\",function(){ //마우스 아웃시\r\n");
      out.write("\t\t\t$(\"#preview\").remove();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(document).on(\"mouseover\",\".thumbnail4\",function(e){ //마우스 오버시\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"body\").append(\"<p id='preview'><img src='/common/img/4.jpg'\"+ $(this).attr(\"src\") +\"' width='100px' /></p>\"); //보여줄 이미지를 선언\t\t\t\t\t \r\n");
      out.write("\t\t\t$(\"#preview\")\r\n");
      out.write("\t\t\t\t.css(\"top\",(e.pageY - xOffset) + \"px\")\r\n");
      out.write("\t\t\t\t.css(\"left\",(e.pageX + yOffset) + \"px\")\r\n");
      out.write("\t\t\t\t.fadeIn(\"fast\"); //미리보기 화면 설정 셋팅\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(document).on(\"mousemove\",\".thumbnail4\",function(e){ //마우스 이동시\r\n");
      out.write("\t\t\t$(\"#preview\")\r\n");
      out.write("\t\t\t\t.css(\"top\",(e.pageY - xOffset) + \"px\")\r\n");
      out.write("\t\t\t\t.css(\"left\",(e.pageX + yOffset) + \"px\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(document).on(\"mouseout\",\".thumbnail4\",function(){ //마우스 아웃시\r\n");
      out.write("\t\t\t$(\"#preview\").remove();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(document).on(\"mouseover\",\".thumbnail5\",function(e){ //마우스 오버시\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"body\").append(\"<p id='preview'><img src='/common/img/5.jpg'\"+ $(this).attr(\"src\") +\"' width='100px' /></p>\"); //보여줄 이미지를 선언\t\t\t\t\t \r\n");
      out.write("\t\t\t$(\"#preview\")\r\n");
      out.write("\t\t\t\t.css(\"top\",(e.pageY - xOffset) + \"px\")\r\n");
      out.write("\t\t\t\t.css(\"left\",(e.pageX + yOffset) + \"px\")\r\n");
      out.write("\t\t\t\t.fadeIn(\"fast\"); //미리보기 화면 설정 셋팅\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(document).on(\"mousemove\",\".thumbnail5\",function(e){ //마우스 이동시\r\n");
      out.write("\t\t\t$(\"#preview\")\r\n");
      out.write("\t\t\t\t.css(\"top\",(e.pageY - xOffset) + \"px\")\r\n");
      out.write("\t\t\t\t.css(\"left\",(e.pageX + yOffset) + \"px\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(document).on(\"mouseout\",\".thumbnail5\",function(){ //마우스 아웃시\r\n");
      out.write("\t\t\t$(\"#preview\").remove();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(document).on(\"mouseover\",\".thumbnail6\",function(e){ //마우스 오버시\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"body\").append(\"<p id='preview'><img src='/common/img/6.jpg'\"+ $(this).attr(\"src\") +\"' width='100px' /></p>\"); //보여줄 이미지를 선언\t\t\t\t\t \r\n");
      out.write("\t\t\t$(\"#preview\")\r\n");
      out.write("\t\t\t\t.css(\"top\",(e.pageY - xOffset) + \"px\")\r\n");
      out.write("\t\t\t\t.css(\"left\",(e.pageX + yOffset) + \"px\")\r\n");
      out.write("\t\t\t\t.fadeIn(\"fast\"); //미리보기 화면 설정 셋팅\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(document).on(\"mousemove\",\".thumbnail6\",function(e){ //마우스 이동시\r\n");
      out.write("\t\t\t$(\"#preview\")\r\n");
      out.write("\t\t\t\t.css(\"top\",(e.pageY - xOffset) + \"px\")\r\n");
      out.write("\t\t\t\t.css(\"left\",(e.pageX + yOffset) + \"px\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(document).on(\"mouseout\",\".thumbnail6\",function(){ //마우스 아웃시\r\n");
      out.write("\t\t\t$(\"#preview\").remove();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(document).on(\"mouseover\",\".thumbnail7\",function(e){ //마우스 오버시\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"body\").append(\"<p id='preview'><img src='/common/img/7.jpg'\"+ $(this).attr(\"src\") +\"' width='100px' /></p>\"); //보여줄 이미지를 선언\t\t\t\t\t \r\n");
      out.write("\t\t\t$(\"#preview\")\r\n");
      out.write("\t\t\t\t.css(\"top\",(e.pageY - xOffset) + \"px\")\r\n");
      out.write("\t\t\t\t.css(\"left\",(e.pageX + yOffset) + \"px\")\r\n");
      out.write("\t\t\t\t.fadeIn(\"fast\"); //미리보기 화면 설정 셋팅\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(document).on(\"mousemove\",\".thumbnail7\",function(e){ //마우스 이동시\r\n");
      out.write("\t\t\t$(\"#preview\")\r\n");
      out.write("\t\t\t\t.css(\"top\",(e.pageY - xOffset) + \"px\")\r\n");
      out.write("\t\t\t\t.css(\"left\",(e.pageX + yOffset) + \"px\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(document).on(\"mouseout\",\".thumbnail7\",function(){ //마우스 아웃시\r\n");
      out.write("\t\t\t$(\"#preview\").remove();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(document).on(\"mouseover\",\".thumbnail8\",function(e){ //마우스 오버시\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"body\").append(\"<p id='preview'><img src='/common/img/8.jpg'\"+ $(this).attr(\"src\") +\"' width='100px' /></p>\"); //보여줄 이미지를 선언\t\t\t\t\t \r\n");
      out.write("\t\t\t$(\"#preview\")\r\n");
      out.write("\t\t\t\t.css(\"top\",(e.pageY - xOffset) + \"px\")\r\n");
      out.write("\t\t\t\t.css(\"left\",(e.pageX + yOffset) + \"px\")\r\n");
      out.write("\t\t\t\t.fadeIn(\"fast\"); //미리보기 화면 설정 셋팅\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(document).on(\"mousemove\",\".thumbnail8\",function(e){ //마우스 이동시\r\n");
      out.write("\t\t\t$(\"#preview\")\r\n");
      out.write("\t\t\t\t.css(\"top\",(e.pageY - xOffset) + \"px\")\r\n");
      out.write("\t\t\t\t.css(\"left\",(e.pageX + yOffset) + \"px\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(document).on(\"mouseout\",\".thumbnail8\",function(){ //마우스 아웃시\r\n");
      out.write("\t\t\t$(\"#preview\").remove();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(document).on(\"mouseover\",\".thumbnail9\",function(e){ //마우스 오버시\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"body\").append(\"<p id='preview'><img src='/common/img/9.jpg'\"+ $(this).attr(\"src\") +\"' width='100px' /></p>\"); //보여줄 이미지를 선언\t\t\t\t\t \r\n");
      out.write("\t\t\t$(\"#preview\")\r\n");
      out.write("\t\t\t\t.css(\"top\",(e.pageY - xOffset) + \"px\")\r\n");
      out.write("\t\t\t\t.css(\"left\",(e.pageX + yOffset) + \"px\")\r\n");
      out.write("\t\t\t\t.fadeIn(\"fast\"); //미리보기 화면 설정 셋팅\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(document).on(\"mousemove\",\".thumbnail9\",function(e){ //마우스 이동시\r\n");
      out.write("\t\t\t$(\"#preview\")\r\n");
      out.write("\t\t\t\t.css(\"top\",(e.pageY - xOffset) + \"px\")\r\n");
      out.write("\t\t\t\t.css(\"left\",(e.pageX + yOffset) + \"px\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(document).on(\"mouseout\",\".thumbnail9\",function(){ //마우스 아웃시\r\n");
      out.write("\t\t\t$(\"#preview\").remove();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(document).on(\"mouseover\",\".thumbnail10\",function(e){ //마우스 오버시\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"body\").append(\"<p id='preview'><img src='/common/img/10.jpg'\"+ $(this).attr(\"src\") +\"' width='100px' /></p>\"); //보여줄 이미지를 선언\t\t\t\t\t \r\n");
      out.write("\t\t\t$(\"#preview\")\r\n");
      out.write("\t\t\t\t.css(\"top\",(e.pageY - xOffset) + \"px\")\r\n");
      out.write("\t\t\t\t.css(\"left\",(e.pageX + yOffset) + \"px\")\r\n");
      out.write("\t\t\t\t.fadeIn(\"fast\"); //미리보기 화면 설정 셋팅\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(document).on(\"mousemove\",\".thumbnail10\",function(e){ //마우스 이동시\r\n");
      out.write("\t\t\t$(\"#preview\")\r\n");
      out.write("\t\t\t\t.css(\"top\",(e.pageY - xOffset) + \"px\")\r\n");
      out.write("\t\t\t\t.css(\"left\",(e.pageX + yOffset) + \"px\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(document).on(\"mouseout\",\".thumbnail10\",function(){ //마우스 아웃시\r\n");
      out.write("\t\t\t$(\"#preview\").remove();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(document).on(\"mouseover\",\".thumbnail11\",function(e){ //마우스 오버시\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"body\").append(\"<p id='preview'><img src='/common/img/11.jpg'\"+ $(this).attr(\"src\") +\"' width='100px' /></p>\"); //보여줄 이미지를 선언\t\t\t\t\t \r\n");
      out.write("\t\t\t$(\"#preview\")\r\n");
      out.write("\t\t\t\t.css(\"top\",(e.pageY - xOffset) + \"px\")\r\n");
      out.write("\t\t\t\t.css(\"left\",(e.pageX + yOffset) + \"px\")\r\n");
      out.write("\t\t\t\t.fadeIn(\"fast\"); //미리보기 화면 설정 셋팅\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(document).on(\"mousemove\",\".thumbnail11\",function(e){ //마우스 이동시\r\n");
      out.write("\t\t\t$(\"#preview\")\r\n");
      out.write("\t\t\t\t.css(\"top\",(e.pageY - xOffset) + \"px\")\r\n");
      out.write("\t\t\t\t.css(\"left\",(e.pageX + yOffset) + \"px\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(document).on(\"mouseout\",\".thumbnail11\",function(){ //마우스 아웃시\r\n");
      out.write("\t\t\t$(\"#preview\").remove();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(document).on(\"mouseover\",\".thumbnail12\",function(e){ //마우스 오버시\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"body\").append(\"<p id='preview'><img src='/common/img/12.jpg'\"+ $(this).attr(\"src\") +\"' width='100px' /></p>\"); //보여줄 이미지를 선언\t\t\t\t\t \r\n");
      out.write("\t\t\t$(\"#preview\")\r\n");
      out.write("\t\t\t\t.css(\"top\",(e.pageY - xOffset) + \"px\")\r\n");
      out.write("\t\t\t\t.css(\"left\",(e.pageX + yOffset) + \"px\")\r\n");
      out.write("\t\t\t\t.fadeIn(\"fast\"); //미리보기 화면 설정 셋팅\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(document).on(\"mousemove\",\".thumbnail12\",function(e){ //마우스 이동시\r\n");
      out.write("\t\t\t$(\"#preview\")\r\n");
      out.write("\t\t\t\t.css(\"top\",(e.pageY - xOffset) + \"px\")\r\n");
      out.write("\t\t\t\t.css(\"left\",(e.pageX + yOffset) + \"px\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(document).on(\"mouseout\",\".thumbnail12\",function(){ //마우스 아웃시\r\n");
      out.write("\t\t\t$(\"#preview\").remove();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(document).on(\"mouseover\",\".thumbnail13\",function(e){ //마우스 오버시\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"body\").append(\"<p id='preview'><img src='/common/img/13.jpg'\"+ $(this).attr(\"src\") +\"' width='100px' /></p>\"); //보여줄 이미지를 선언\t\t\t\t\t \r\n");
      out.write("\t\t\t$(\"#preview\")\r\n");
      out.write("\t\t\t\t.css(\"top\",(e.pageY - xOffset) + \"px\")\r\n");
      out.write("\t\t\t\t.css(\"left\",(e.pageX + yOffset) + \"px\")\r\n");
      out.write("\t\t\t\t.fadeIn(\"fast\"); //미리보기 화면 설정 셋팅\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(document).on(\"mousemove\",\".thumbnail13\",function(e){ //마우스 이동시\r\n");
      out.write("\t\t\t$(\"#preview\")\r\n");
      out.write("\t\t\t\t.css(\"top\",(e.pageY - xOffset) + \"px\")\r\n");
      out.write("\t\t\t\t.css(\"left\",(e.pageX + yOffset) + \"px\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(document).on(\"mouseout\",\".thumbnail13\",function(){ //마우스 아웃시\r\n");
      out.write("\t\t\t$(\"#preview\").remove();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(document).on(\"mouseover\",\".thumbnail14\",function(e){ //마우스 오버시\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"body\").append(\"<p id='preview'><img src='/common/img/14.jpg'\"+ $(this).attr(\"src\") +\"' width='100px' /></p>\"); //보여줄 이미지를 선언\t\t\t\t\t \r\n");
      out.write("\t\t\t$(\"#preview\")\r\n");
      out.write("\t\t\t\t.css(\"top\",(e.pageY - xOffset) + \"px\")\r\n");
      out.write("\t\t\t\t.css(\"left\",(e.pageX + yOffset) + \"px\")\r\n");
      out.write("\t\t\t\t.fadeIn(\"fast\"); //미리보기 화면 설정 셋팅\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(document).on(\"mousemove\",\".thumbnail14\",function(e){ //마우스 이동시\r\n");
      out.write("\t\t\t$(\"#preview\")\r\n");
      out.write("\t\t\t\t.css(\"top\",(e.pageY - xOffset) + \"px\")\r\n");
      out.write("\t\t\t\t.css(\"left\",(e.pageX + yOffset) + \"px\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(document).on(\"mouseout\",\".thumbnail14\",function(){ //마우스 아웃시\r\n");
      out.write("\t\t\t$(\"#preview\").remove();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("        \r\n");
      out.write("   });\r\n");
      out.write("    </script>\r\n");
      out.write(" \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div>\r\n");
      out.write("\t\t\t<h3>결재라인지정</h3>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("<div class=\"table_wrap\">\r\n");
      out.write("<table>\r\n");
      out.write("\t<form id=\"ealine\" name=\"ealine\">  \r\n");
      out.write("    <div class=\"tree_box\">\r\n");
      out.write("    <div class=\"con\">\r\n");
      out.write("        <ul id=\"tree_menu\" class=\"tree_menu\">\r\n");
      out.write("        \t<li class=\"depth_1\"><strong>총장</strong>\r\n");
      out.write("                <ul class=\"depth_2\">\r\n");
      out.write("                \t<li>\r\n");
      out.write("                        <a href=\"#none\"><em>폴더</em> 총장</a>\r\n");
      out.write("                        <ul class=\"depth_3\">\r\n");
      out.write("                            <li data=\"김태평\" class=\"end\"><a href=\"#none\" class=\"thumbnail\" height='50px'>김태평</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"depth_1\"><strong>기획처</strong>\r\n");
      out.write("                <ul class=\"depth_2\" >\r\n");
      out.write("                \t<li>\r\n");
      out.write("                        <a href=\"#none\"><em>폴더</em> 기획처장</a>\r\n");
      out.write("                        <ul class=\"depth_3\">\r\n");
      out.write("                            <li data=\"정상희\" class=\"end\"><a href=\"#none\" class=\"thumbnail2\" height='50px'>정상희</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"#none\"><em>폴더</em> 기획팀</a>\r\n");
      out.write("                        <ul class=\"depth_3\">\r\n");
      out.write("                            <li data=\"최성남\" class=\"end\"><a href=\"#none\" class=\"thumbnail3\" height='50px'>팀장 최성남</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"last\">\r\n");
      out.write("                        <a href=\"#none\"><em>폴더</em> 홍보팀</a>\r\n");
      out.write("                        <ul class=\"depth_3\">\r\n");
      out.write("                            <li data=\"김영권\" class=\"end\"><a href=\"#none\" class=\"thumbnail4\" height='50px'>팀장 김영권</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"depth_1\"><strong>교학처</strong>\r\n");
      out.write("                <ul class=\"depth_2\">\r\n");
      out.write("                \t<li>\r\n");
      out.write("                        <a href=\"#none\"><em>폴더</em> 교학처장</a>\r\n");
      out.write("                        <ul class=\"depth_3\">\r\n");
      out.write("                            <li data=\"박근덕\" class=\"end\"><a href=\"#none\" class=\"thumbnail5\" height='50px'>박근덕</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"#none\"><em>폴더</em> 입학관리팀</a>\r\n");
      out.write("                        <ul class=\"depth_3\">\r\n");
      out.write("                            <li data=\"서인성\" class=\"end\"><a href=\"#none\" class=\"thumbnail6\" height='50px'>팀장 서인성</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"#none\"><em>폴더</em> 교무팀</a>\r\n");
      out.write("                        <ul class=\"depth_3\">\r\n");
      out.write("                            <li data=\"양진욱\" class=\"end\"><a href=\"#none\" class=\"thumbnail7\" height='50px'>팀장 양진욱</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"last\">\r\n");
      out.write("                        <a href=\"#none\"><em>폴더</em> 학사지원팀</a>\r\n");
      out.write("                        <ul class=\"depth_3\">\r\n");
      out.write("                            <li data=\"최용선\" class=\"end\"><a href=\"#none\" class=\"thumbnail8\" height='50px'>팀장 최용선</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"depth_1\"><strong>사무처</strong>\r\n");
      out.write("                <ul class=\"depth_2\" >\r\n");
      out.write("                \t<li>\r\n");
      out.write("                        <a href=\"#none\"><em>폴더</em> 사무처장</a>\r\n");
      out.write("                        <ul class=\"depth_3\">\r\n");
      out.write("                            <li data=\"조대진\" class=\"end\"><a href=\"#none\" class=\"thumbnail9\" height='50px'>조대진</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"#none\"><em>폴더</em> 총무팀</a>\r\n");
      out.write("                        <ul class=\"depth_3\">\r\n");
      out.write("                            <li data=\"문찬미\" class=\"end\"><a href=\"#none\" class=\"thumbnail10\" height='50px'>팀장 문찬미</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"last\">\r\n");
      out.write("                        <a href=\"#none\"><em>폴더</em> 재무팀</a>\r\n");
      out.write("                        <ul class=\"depth_3\">\r\n");
      out.write("                            <li data=\"김나미\" class=\"end\"><a href=\"#none\" class=\"thumbnail11\" height='50px'>팀장 김나미</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"depth_1\"><strong>국제협력처</strong>\r\n");
      out.write("                <ul class=\"depth_2\" >\r\n");
      out.write("                \t<li>\r\n");
      out.write("                        <a href=\"#none\"><em>폴더</em> 국제협력처장</a>\r\n");
      out.write("                        <ul class=\"depth_3\">\r\n");
      out.write("                            <li data=\"안진호\" class=\"end\"><a href=\"#none\" class=\"thumbnail12\" height='50px'>안진호</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"#none\"><em>폴더</em> 국제교류팀</a>\r\n");
      out.write("                        <ul class=\"depth_3\">\r\n");
      out.write("                            <li data=\"조정현\" class=\"end\"><a href=\"#none\" class=\"thumbnail13\" height='50px'>팀장 조정현</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"last\">\r\n");
      out.write("                        <a href=\"#none\"><em>폴더</em> 국제학생지원팀</a>\r\n");
      out.write("                        <ul class=\"depth_3\">\r\n");
      out.write("                            <li data=\"황미혜\" class=\"end\"><a href=\"#none\" class=\"thumbnail14\" height='50px'>팀장 황미혜</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>            \r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write(" \t\t\r\n");
      out.write("\t\r\n");
      out.write("<!--//트리메뉴-->\r\n");
      out.write(" </form>\r\n");
      out.write(" \t\t<tr>\r\n");
      out.write(" \t\t\t<td>결재자\r\n");
      out.write(" \t\t\t<input type=\"text\" name=\"person\" id=\"person\" readonly></td>\r\n");
      out.write(" \t\t\t\t\t \t\r\n");
      out.write(" \t\t<td>\t\t\t\r\n");
      out.write("\t\t\t<input type=\"button\" class=grey_btn name=\"close\" id=\"close\" value=\"닫기 \">\r\n");
      out.write("\t\t\t<input type=\"button\" class=blue_btn name=\"check\" id=\"check\" value=\"추가\"></td>\t\r\n");
      out.write("\t\t</tr>\r\n");
      out.write(" </table>\r\n");
      out.write(" </div>\r\n");
      out.write(" </div>\r\n");
      out.write(" \t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
