/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.12
 * Generated at: 2021-03-30 11:42:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.ea;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import com.uniform.ea.approval.vo.EaDocumentVO;
import com.uniform.ea.approval.vo.PageVO;
import com.uniform.em.common.vo.EmCommonVO;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, target-densityDpi=medium-dpi\">\r\n");
      out.write("\t\t<title>전자결재메인</title>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- Reset CSS --> \r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"/cssExample/css/reset_normalize.css\" media=\"all\">\r\n");
      out.write("\t\t<!-- Design CSS -->\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"/cssExample/css/style_common.css\" media=\"all\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"/cssExample/css/style_contents.css\" media=\"all\">\r\n");
      out.write("\t\t<!-- Layout CSS -->\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"/cssExample/css/layout_main.css\" media=\"all\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"/cssExample/css/layout_sub.css\" media=\"all\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"/cssExample/css/layout_responsive.css\" media=\"all\">\r\n");
      out.write("\t\t<!-- Script --> \r\n");
      out.write("\t\t<script src=\"/cssExample/js/jquery.js\"></script>\r\n");
      out.write("\t\t<script src=\"/cssExample/js/jquery.ui.js\"></script>\r\n");
      out.write("\t\t<script src=\"/cssExample/js/jquery.bxslider.js\"></script>\r\n");
      out.write("\t\t<script src=\"/cssExample/js/common.js\"></script>  \r\n");
      out.write("\t\t<script src=\"/cssExample/js/custom.js\"></script>\r\n");
      out.write("\t\t<script src=\"/cssExample/js/main2.js\"></script>  \r\n");
      out.write("\t\t<script src=\"/cssExample/js/masonry.pkgd.js\"></script>\r\n");

	HttpSession hs = request.getSession(true);
	String i_no = (String)hs.getAttribute("i_no");
	boolean sessionBool = false;
	sessionBool = i_no==null;
	if(sessionBool){

      out.write("\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\talert(\"세션이 만료되었습니다. 다시 로그인 해주세요\");\r\n");
      out.write("\t\t\tlocation.href=\"/index.jsp\";\r\n");
      out.write("\t\t</script>\r\n");

	}else{
			
		//결재중 리스트 
		Object obj2 = request.getAttribute("ingList");
		List<PageVO> ingList = (List<PageVO>)obj2;
		String do_docno = "";
		String do_type = "";
		String do_writer = "";
		String do_title = "";
		String do_insertdate = "";
		String do_lineno = "";
		String do_aprno = "";
		String ea_aprno = "";
		String ea_stateno = "";
		
		//결재할 리스트
		Object obj3 = request.getAttribute("toList");
		List<PageVO> toList = (List<PageVO>)obj3;
		
		//반려함 리스트
		Object obj4 = request.getAttribute("reList");
		List<PageVO> reList = (List<PageVO>)obj4;
		
		//완료함 리스트
		Object obj5 = request.getAttribute("finList");
		List<PageVO> finList = (List<PageVO>)obj5;
		
		EmCommonVO ecvo = (EmCommonVO)request.getAttribute("ecvo");
		

      out.write("\r\n");
      out.write("\t\t<script type=\"text/javascript\"\r\n");
      out.write("\t\t\t\tsrc=\"https://code.jquery.com/jquery-1.11.0.min.js\"></script>\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t\t$(document).ready(function(){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//기안서 작성 페이지로 이동\r\n");
      out.write("\t\t\t\t$(\"#gian_btn\").click(function(){\r\n");
      out.write("\t\t\t\t\tconsole.log(\"main뷰의 gian_btn 클릭\");\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tvar popWidth = 300;\r\n");
      out.write("\t\t\t\t\tvar popHeight = 200;\r\n");
      out.write("\t\t\t\t\tvar popX = (window.screen.width/2) - (popWidth/2);\r\n");
      out.write("\t\t\t\t\tvar popY = (window.screen.height/2) - (popHeight/2);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\twindow.name = \"main\";\r\n");
      out.write("\t\t\t\t\twindow.open(\"\", \"pop\", \"width=\" +popWidth+ \",height=\" +popHeight+ \",left=\" +popX+ \",top=\" +popY);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$(\"#goWriteForm\").attr(\"action\", \"/ea/goGianPop.uni\");\r\n");
      out.write("\t\t\t\t\t$(\"#goWriteForm\").attr(\"target\", \"pop\");\r\n");
      out.write("\t\t\t\t\t$(\"#goWriteForm\").submit();\r\n");
      out.write("\t\t\t\t\t//안되면 goWriteForm으로 수정\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//품의서 작성 페이지로 이동\r\n");
      out.write("\t            $(\"#poom_btn\").click(function(){\r\n");
      out.write("\t                 console.log(\"main뷰의 poom_btn 클릭\");\r\n");
      out.write("\t                 window.open(\"\", \"pop\", \"width=500, height=350\");\r\n");
      out.write("\t                 $(\"#goWriteForm\").attr(\"action\", \"/ea/goPoomPop.uni\");\r\n");
      out.write("\t                 $(\"#goWriteForm\").attr(\"target\", \"pop\");\r\n");
      out.write("\t                 $(\"#goWriteForm\").submit();\r\n");
      out.write("\t              });\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//휴가계 작성 페이지로 이동\r\n");
      out.write("\t\t\t\t$(\"#vaca_btn\").click(function(){\r\n");
      out.write("\t\t\t\t\t$(\"#ea_linename\").val(\"휴가계\");\r\n");
      out.write("\t\t\t\t\t$(\"#linenameForm\").attr(\"action\", \"/ea/goVacaWrite.uni\");\r\n");
      out.write("\t\t\t\t\t$(\"#linenameForm\").submit();\r\n");
      out.write("\t\t\t\t});\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//내가쓴 문서 상세보기 (결재할,반려함,완료함)\r\n");
      out.write("\t\t\t\t$(\".goDetail\").click(function(){\r\n");
      out.write("\t\t\t\t\tvar docno = $(this).parents(\"tr\").attr(\"data-num\");\r\n");
      out.write("\t\t\t\t\t$(\"#do_docno\").val(docno);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tvar doctype = $(this).parents(\"tr\").attr(\"data-type\");\r\n");
      out.write("\t\t\t\t\tif(doctype.match(\"기안\")){\r\n");
      out.write("\t\t\t\t\t\t$(\"#goDetailForm\").attr(\"action\", \"/ea/giDetailSelect.uni\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tif(doctype.match(\"휴가\")){\r\n");
      out.write("\t\t\t\t\t\t$(\"#goDetailForm\").attr(\"action\", \"/ea/vaDetailSelect.uni\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$(\"#goDetailForm\").submit();\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//내가 결재할 문서 상세보기\r\n");
      out.write("\t\t\t\t$(\".goToDetail\").click(function(){\r\n");
      out.write("\t\t\t\t\tvar docno = $(this).parents(\"tr\").attr(\"data-num\");\r\n");
      out.write("\t\t\t\t\t$(\"#do_docno\").val(docno);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tvar doctype = $(this).parents(\"tr\").attr(\"data-type\");\r\n");
      out.write("\t\t\t\t\tif(doctype.match(\"기안\")){\r\n");
      out.write("\t\t\t\t\t\t$(\"#goDetailForm\").attr(\"action\", \"/ea/giToSelect.uni\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tif(doctype.match(\"휴가\")){\r\n");
      out.write("\t\t\t\t\t\t$(\"#goDetailForm\").attr(\"action\", \"/ea/vaToSelect.uni\");\r\n");
      out.write("\t\t\t\t\t}\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$(\"#goDetailForm\").submit();\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//결재할문서 메뉴 이동\r\n");
      out.write("\t\t\t\t$(\".willbox\").click(function(){\r\n");
      out.write("\t\t\t\t\t$(\"#goBox\").attr(\"action\", \"/ea/willbox.uni\");\r\n");
      out.write("\t\t\t\t\t$(\"#goMenu\").submit();\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//결재중문서 메뉴 이동\r\n");
      out.write("\t\t\t\t$(\".menuIng\").click(function(){\r\n");
      out.write("\t\t\t\t\t$(\"#goMenu\").attr(\"action\", \"/ea/goMenuIng.uni\");\r\n");
      out.write("\t\t\t\t\t$(\"#goMenu\").submit();\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//반려함 메뉴 이동\r\n");
      out.write("\t\t\t\t$(\".menuRe\").click(function(){\r\n");
      out.write("\t\t\t\t\t$(\"#goMenu\").attr(\"action\", \"/ea/goMenuRe.uni\");\r\n");
      out.write("\t\t\t\t\t$(\"#goMenu\").submit();\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//완료함 메뉴 이동\r\n");
      out.write("\t\t\t\t$(\".menuFin\").click(function(){\r\n");
      out.write("\t\t\t\t\t$(\"#goMenu\").attr(\"action\", \"/ea/goMenuFin.uni\");\r\n");
      out.write("\t\t\t\t\t$(\"#goMenu\").submit();\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t$(\"#ed_btn\").click(function(){\r\n");
      out.write("\t\t\t\t\t$(\"#goMenu\").attr(\"action\", \"/ea/goMenuEd.uni\");\r\n");
      out.write("\t\t\t\t\t$(\"#goMenu\").submit();\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//메뉴\r\n");
      out.write("\t\t\t\t$(\".more\").click(function(){\r\n");
      out.write("\t\t\t\t\tif($(\".moreli\").is(\":visible\")){\r\n");
      out.write("\t\t\t\t\t\t$(\".moreli\").slideUp();\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t$(\".moreli\").slideDown();\r\n");
      out.write("\t\t\t\t\t}   \r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tfunction linename(ea_linename){\r\n");
      out.write("\t\t\t\t//alert(\"확인 > \" + ea_linename);\r\n");
      out.write("\t\t\t\t$(\"#ea_linename\").val(ea_linename);\r\n");
      out.write("\t\t\t\t$(\"#linenameForm\").attr(\"action\", \"/ea/goGianWrite.uni\");\r\n");
      out.write("\t\t\t\t$(\"#linenameForm\").submit();\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t //품의서 결재라인 구분         \r\n");
      out.write("\t         function linename1(ea_linename){\r\n");
      out.write("\t        \t if(ea_linename==\"품의\"){\r\n");
      out.write("\t        \t $(\"#ea_linename\").val(ea_linename);\r\n");
      out.write("\t        \t $(\"#linenameForm\").attr(\"action\", \"/ea/goPoomWrite.uni\");\r\n");
      out.write("\t        \t $(\"#linenameForm\").submit();\r\n");
      out.write("\t        \t }else{\r\n");
      out.write("\t        \t\t $(\"#ea_linename\").val(ea_linename);\r\n");
      out.write("\t            \t $(\"#linenameForm\").attr(\"action\", \"/ea/goPoomWriteF.uni\");\r\n");
      out.write("\t            \t $(\"#linenameForm\").submit();}\r\n");
      out.write("\t         }\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- CSS -->\r\n");
      out.write("\t\t<style type=\"text/css\">\r\n");
      out.write("\t\t\tbutton{\r\n");
      out.write(" \t\t\t\tfont-size: 17px; \r\n");
      out.write("\t\t\t    border: none;\r\n");
      out.write(" \t\t\t    padding: 0px 5px; \r\n");
      out.write("\t\t\t    text-align: center;\r\n");
      out.write("\t\t\t    text-decoration: none;\r\n");
      out.write("\t\t\t    display: inline-block;\r\n");
      out.write("\t\t\t    margin: 15px;\r\n");
      out.write("\t\t\t    cursor: pointer;\r\n");
      out.write("\t\t\t    border-radius:10px 10px 10px 10px; \r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t.t1, .t2, .t3, .t4{\r\n");
      out.write("\t\t\t\twidth: 450px;\r\n");
      out.write("\t\t\t\tborder-collapse:collapse;\r\n");
      out.write("\t\t\t\tmargin:0;\r\n");
      out.write("\t\t\t\tpadding:0;\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t.t1 tr, .t2 tr, .t3 tr, .t4 tr{\r\n");
      out.write("\t\t\t\tborder-bottom: 1px solid #e6e6e6;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\ttable .menu_title{\r\n");
      out.write("\t\t\t\theight: 45px;\r\n");
      out.write("\t\t\t\tfont-size: 17px;\r\n");
      out.write("\t\t\t\tfont-weight: bold;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write(" \t\t\t/*내용의 5줄 높이 */\r\n");
      out.write("\t\t\ttable tr {\r\n");
      out.write("\t\t\t\theight: 30px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write(" \t\t\t/*분류하는부분 높이 */\r\n");
      out.write("\t\t\ttable .contents{\r\n");
      out.write("\t\t\t\theight: 25px;\r\n");
      out.write("\t\t\t\tfont-size: 15px;\r\n");
      out.write("\t\t\t\tbackground-color: #f4f5f7;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t.whole .none{\r\n");
      out.write("\t\t\t\twidth: 15px;\r\n");
      out.write("\t\t\t}\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\ttable .con_type{\r\n");
      out.write("\t\t\t\twidth: 25px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\ttable .con_title{\r\n");
      out.write("\t\t\t\twidth: 140px;\r\n");
      out.write("\t\t\t}\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\ttable .con_state{\r\n");
      out.write("\t\t\t\twidth: 30px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\ttable .con_hu{\r\n");
      out.write("\t\t\t\twidth: 30px;\r\n");
      out.write("\t\t\t}\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t</style>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t//반응형에 따른 BODY CSS 교체\r\n");
      out.write("\t\t//제이쿼리 DOM 탐색 시간 관계로 (폴링에 따른 적용시간 지연) Common.js에서 옮김.\r\n");
      out.write("\t\tfunction respondCSS() {\r\n");
      out.write("\t\t\tvar windowWidth = $(window).width();\r\n");
      out.write("\r\n");
      out.write("\t\t\tif (windowWidth < 430) { \r\n");
      out.write("\t\t\t\t$(document.body).addClass('mobile');\r\n");
      out.write("\t\t\t\t$(document.body).addClass('tablet');\r\n");
      out.write("\t\t\t\t$(document.body).removeClass('desktop');\r\n");
      out.write("\t\t\t\t$(document.body).removeClass('desktop02');\r\n");
      out.write("\t\t\t\t$(document.body).removeClass('desktop03');\r\n");
      out.write("\t\t\t\t$(\".box_slider\").appendTo('#bn_banners');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse if (windowWidth < 860) { \r\n");
      out.write("\t\t\t\t$(document.body).addClass('tablet');\r\n");
      out.write("\t\t\t\t$(document.body).removeClass('mobile');\r\n");
      out.write("\t\t\t\t$(document.body).removeClass('desktop');\r\n");
      out.write("\t\t\t\t$(document.body).removeClass('desktop02');\r\n");
      out.write("\t\t\t\t$(document.body).removeClass('desktop03');\r\n");
      out.write("\t\t\t\t$(\"#box_latest\").append($('.box_slider'));\r\n");
      out.write("\t\t\t\t// if(window.matchMedia(\"(orientation:portrait)\").matches){\r\n");
      out.write("\t\t\t\t\t// $(document.body).removeClass('desktop03');\r\n");
      out.write("\t\t\t\t// }\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse if (windowWidth < 1024) { \r\n");
      out.write("\t\t\t\t$(document.body).addClass('desktop');\r\n");
      out.write("\t\t\t\t$(document.body).addClass('desktop02');\r\n");
      out.write("\t\t\t\t$(document.body).removeClass('mobile');\r\n");
      out.write("\t\t\t\t$(document.body).removeClass('tablet');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse if (windowWidth < 1190) { \r\n");
      out.write("\t\t\t\t$(document.body).addClass('desktop');\r\n");
      out.write("\t\t\t\t$(document.body).addClass('desktop');\r\n");
      out.write("\t\t\t\t$(document.body).addClass('desktop03');\r\n");
      out.write("\t\t\t\t$(document.body).removeClass('mobile');\r\n");
      out.write("\t\t\t\t$(document.body).removeClass('tablet');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse {\r\n");
      out.write("\t\t\t\t$(document.body).addClass('desktop');\r\n");
      out.write("\t\t\t\t$(document.body).removeClass('mobile');\r\n");
      out.write("\t\t\t\t$(document.body).removeClass('tablet');\r\n");
      out.write("// \t\t\t\t$(document.body).removeClass('desktop02');\r\n");
      out.write("\t\t\t\t$(document.body).removeClass('desktop03');\r\n");
      out.write("\t\t\t\t$(\"#box_latest\").append($('.box_slider'));\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t$(window).on(\"orientationchange load resize \", respondCSS);\r\n");
      out.write("\t\trespondCSS();\r\n");
      out.write("\r\n");
      out.write("\t</script>\t\r\n");
      out.write("\r\n");
      out.write("\t<!-- 스킵 네비게이션 -->\r\n");
      out.write("\t<div id=\"box_skip\">\r\n");
      out.write("\t\t<h2 class=\"hiddenT\">Skip Navigation</h2>\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li><a href=\"#skipnav\">본문 바로가기</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#navFirst\">주메뉴 바로가기</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- // 스킵 네비게이션 -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- 헤더 -->\r\n");
      out.write("\t<header id=\"box_wrap_header\">\r\n");
      out.write("\t\t<div id=\"box_header\">\r\n");
      out.write("\t\t\t<!-- GNB -->\r\n");
      out.write("\t\t\t<div class=\"box_gnb\">\r\n");
      out.write("\t\t\t\t<ul class=\"list_gnb\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">");
      out.print(ecvo.getI_nameKr() + " " + ecvo.getI_no() );
      out.write("</a></li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");

				if(i_no.indexOf("E")>-1){

      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/main/goMyInfo.uni\">MyPage</a>\r\n");

				}

      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">LogOut</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- // GNB -->\r\n");
      out.write("\t\t\t<!-- LNB -->\r\n");
      out.write("\t\t\t<div class=\"box_lnb\">\r\n");
      out.write("\t\t\t\t<div class=\"wrap1200 box_logo\">\r\n");
      out.write("\t\t\t\t\t<h2 style=\"font-size:4.5em;\"> \r\n");
      out.write("\t\t\t\t\t\t<a href=\"/main/goMain.uni\"><img src=\"/cssExample/img/uniform_logo1.jpg\" width=\"209px\" style=\"margin:10px 0\" alt=\"유니폼 로고\"></a>\r\n");
      out.write("\t\t\t\t\t</h2>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn_all_menu\">전체메뉴 열기</button>\r\n");
      out.write("\t\t\t\t<nav>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li style=\"background-image: none;\"><a href=\"#\" id=\"navFirst\">학교정보</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/ea/goEaMain.uni\">전자결재</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/main/pmGoPlanMain.uni\">일정관리</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/si/goSiMain.uni\">학생관리</a> \r\n");
      out.write("\t\t\t\t\t\t</li>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/board/boardList.uni\">공지/게시판</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");

					if(i_no.indexOf("M")>-1){

      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"/em/goEmMain.uni\">인사관리</a>\r\n");

					}else{

      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\">인사관리</a>\r\n");
						
					}

      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</nav>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- // LNB -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<!-- // 헤더 -->\r\n");
      out.write("\t<!-- 헤더 nav --> \r\n");
      out.write("\t<div id=\"nav_header_fix\">\t\r\n");
      out.write("\t\t\t<nav> \r\n");
      out.write("<!-- \t\t<nav id=\"location\"> -->\r\n");
      out.write("<!-- \t\t\t\t<div class=\"nav_title\"> -->\r\n");
      out.write("<!-- \t\t\t\t\t<a href=\"#none\">HOME </a> -->\r\n");
      out.write("<!-- \t\t\t\t\t<a href=\"#none\"> > </a> -->\r\n");
      out.write("<!-- \t\t\t\t\t<a href=\"#none\"> 게시판 </a> -->\r\n");
      out.write("<!-- \t\t\t\t\t<a href=\"#none\"> > </a> -->\r\n");
      out.write("<!-- \t\t\t\t\t<a href=\"#none\"> 게시판 글쓰기</a> -->\r\n");
      out.write("<!-- \t\t\t\t</div> -->\r\n");
      out.write("<!-- \t\t</nav>\t -->\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<div class=\"nav_title\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#none\">HOME</a>\r\n");
      out.write("\t\t\t\t\t</div>  \r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<div class=\"nav_title\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#none\">></a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<div class=\"nav_title\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#none\">전자결재</a>\r\n");
      out.write("\t\t\t\t\t</div>\t\t\t\t\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("<!-- \t\t\t\t<li> -->\r\n");
      out.write("<!-- \t\t\t\t\t<div class=\"nav_title\"> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t<a href=\"#none\">></a> -->\r\n");
      out.write("<!-- \t\t\t\t\t</div> -->\r\n");
      out.write("<!-- \t\t\t\t</li> \t\t -->\r\n");
      out.write("<!-- \t\t\t\t<li>  -->\r\n");
      out.write("<!-- \t\t\t\t\t<div class=\"nav_title\"> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t<a href=\"#none\">게시판 글쓰기</a> -->\r\n");
      out.write("<!-- \t\t\t\t\t</div> -->\r\n");
      out.write("<!-- \t\t\t\t</li> -->\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t\t<div class=\"box_option\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li><button type=\"button\" class=\"zoom_in\">확대</button></li>\r\n");
      out.write("\t\t\t\t<li><button type=\"button\" class=\"zoom_ori\">기본</button></li>\r\n");
      out.write("\t\t\t\t<li><button type=\"button\" class=\"zoom_out\">축소</button></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>  \r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- body -->\r\n");
      out.write("\t<div id=\"box_wrap_body\" class=\"wrap1200\">\r\n");
      out.write("\t\t<div id=\"box_sub\">\r\n");
      out.write("\t\t\t<!-- 사이드바 -->\r\n");
      out.write("\t\t\r\n");
      out.write("<div id=\"box_sidebar\">\r\n");
      out.write("\t<div>   \r\n");
      out.write("\t\t<h2><a href=\"/ea/goEaMain.uni\">전자결재</a></h2>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- SNB -->\r\n");
      out.write("\t<nav>\r\n");
      out.write("\t\t<ul>\t\t\r\n");
      out.write("\t\t\t<li><a class=\"more\">결재문서 작성</a>\t\t\t\r\n");
      out.write("\t\t\t\t<ul class=\"moreli\" style=\"display:none\">\r\n");
      out.write("\t\t\t\t\t<li><a>기안서 작성</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a>품의서 작성</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a>휴가계 작성</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li><a href=\"/ea/willbox.uni\">결재할 문서</a></li> \r\n");
      out.write("\t\t\t<li><a href=\"/ea/goMenuIng.uni\">결재중 문서</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"/ea/goMenuEd.uni\">결재한 문서</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"/ea/goMenuFin.uni\">완료함</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"/ea/goMenuRe.uni\">반려함</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"/ea/goUploadList.uni\">양식 다운로드</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\t<!-- // SNB -->\r\n");
      out.write("</div>\t\r\n");
      out.write("\r\n");
      out.write("<!-- 컨텐츠 -->\r\n");
      out.write("<div id=\"box_conts\">\t\r\n");
      out.write("\t<article id=\"skipnav\">\r\n");
      out.write("\t\t<section class=\"title_cont\">\r\n");
      out.write("<!-- \t\t\t<h2 class=\"title\">전자결재</h2> -->\r\n");
      out.write("\t\t</section> \r\n");
      out.write("\t\t<!-- 컨텐츠 내용 --> \r\n");
      out.write("\t\t<section class=\"\">\r\n");
      out.write("\t\t\t<div id=\"printContents\"> \r\n");
      out.write("\t\t\t\t<section class=\"marB40\">\r\n");
      out.write("\t\t\t\t<!-- 버튼 -->\r\n");
      out.write("\t\t<form name=\"goWriteForm\" id=\"goWriteForm\">\r\n");
      out.write("<!-- \t\t\t<input type=\"button\" name=\"gian_btn\" id=\"gian_btn\" value=\"기안서 작성\"> \r\n");
      out.write("\t\t\t\t<input type=\"button\" name=\"poom_btn\" id=\"poom_btn\" value=\"품의서 작성\">\r\n");
      out.write("\t\t\t\t<input type=\"button\" name=\"vaca_btn\" id=\"vaca_btn\" value=\"휴가계 작성\">-->\r\n");
      out.write("\t\t\t<button type=\"button\" name=\"gian_btn\" id=\"gian_btn\"><img src=\"/ea/common/write.png\" style=\"vertical-align: text-bottom\">&nbsp;&nbsp;기안서 작성&nbsp;</button>\r\n");
      out.write("\t\t\t<button type=\"button\" name=\"poom_btn\" id=\"poom_btn\"><img src=\"/ea/common/write.png\" style=\"vertical-align: text-bottom\">&nbsp;&nbsp;품의서 작성&nbsp;</button> \r\n");
      out.write("\t\t\t<button type=\"button\" name=\"vaca_btn\" id=\"vaca_btn\"><img src=\"/ea/common/write.png\" style=\"vertical-align: text-bottom\">&nbsp;&nbsp;휴가계 작성&nbsp;</button> \r\n");
      out.write("<!-- \t\t\t<input type=\"button\" name=\"ed_btn\" id=\"ed_btn\" value=\"결재한문서\"> -->\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t<table class=\"whole\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<table class=\"t1\">\r\n");
      out.write("\t\t\t\t\t\t<tr class=\"menu_title\">\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"4\" align=\"left\"><span class=\"willbox\">결재할 문서</span></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr class=\"contents\" height=25>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"con_type\">분류</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"con_title\">제목</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"con_state\">상태</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"con_hu\">작성자</td>\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");

				if(toList.size()>0){
					for(int i=0;i<toList.size()&&i<5;i++){
						PageVO pvo = toList.get(i);
						do_docno = pvo.getDo_docno();
						do_type = pvo.getDo_type();
						do_writer = pvo.getDo_writer();
						do_title = pvo.getDo_title();
						do_insertdate = pvo.getDo_insertdate();
						do_lineno = pvo.getDo_lineno();
						ea_stateno = pvo.getEa_stateno();
						do_aprno = pvo.getDo_aprno();
						if(ea_stateno.equals("71")) ea_stateno="대기";
						if(ea_stateno.equals("72")) ea_stateno="1차검토";
						if(ea_stateno.equals("73")) ea_stateno="2차검토";
						
						if(do_title!=null&&do_title!=""){
							if(do_title.length()>8){
								do_title = do_title.substring(0,9) + "...";
							}
						}
						

      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<tr data-num=\"");
      out.print(do_docno);
      out.write("\" data-type=\"");
      out.print(do_type );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t<td>");
      out.print(do_type );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><span class=\"goToDetail\">");
      out.print(do_title );
      out.write("</span></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>");
      out.print(ea_stateno );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>");
      out.print(do_writer );
      out.write("</td>\t\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
					
					}
					for(int m=0;m<5-(toList.size());m++){

      out.write("\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\t\t\t\t\t\t\t\t\t\t\r\n");
					
					}					
				}else{

      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"4\" height=\"151px\" align=\"center\">조회된 문서가 없습니다.</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
					
				}

      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("<td class=\"none\"> </td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<table class=\"t2\">\r\n");
      out.write("\t\t\t\t\t\t<tr class=\"menu_title\">\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"4\" align=\"left\"><span class=\"menuRe\">반려함</span></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<tr class=\"contents\">\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"con_type\">분류</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"con_title\">제목</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"con_state\">상태</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"con_hu\">최종결재자</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");

				if(reList.size()>0){
					for(int j=0;j<reList.size()&&j<5;j++){
						PageVO pvo = reList.get(j);
						do_docno = pvo.getDo_docno();
						do_type = pvo.getDo_type();
						do_writer = pvo.getDo_writer();
						do_title = pvo.getDo_title();
						do_insertdate = pvo.getDo_insertdate();
						ea_stateno = pvo.getEa_stateno();
						ea_aprno = pvo.getEa_aprno();
						
						if(do_title!=null&&do_title!=""){
							if(do_title.length()>8){
								do_title = do_title.substring(0,9) + "...";
							}
						}
					

      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<tr data-num=\"");
      out.print(do_docno);
      out.write("\" data-type=\"");
      out.print(do_type );
      out.write("\" height=\"25\">\r\n");
      out.write("\t\t\t\t\t\t\t<td>");
      out.print(do_type );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><span class=\"goDetail\">");
      out.print(do_title );
      out.write("</span></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>");
      out.print(ea_stateno );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>");
      out.print(ea_aprno );
      out.write("</td>\t\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
						
					}
					for(int n=0;n<5-(reList.size());n++){

      out.write("\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\t\t\t\t\t\t\t\t\t\t\r\n");
					
					}
				}else{

      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"4\" height=\"151px\" align=\"center\">조회된 문서가 없습니다.</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
					
				}

      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>\t\r\n");
      out.write("\t\t\t\t<!-- 상세페이지이동 -->\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<table class=\"t3\">\r\n");
      out.write("\t\t\t\t\t\t<tr class=\"menu_title\">\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"4\" align=\"left\"><span class=\"menuIng\">결재중 문서</span></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<tr class=\"contents\">\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"con_type\">분류</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"con_title\">제목</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"con_state\">상태</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"con_hu\">현결재자</td>\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");

				if(ingList.size()>0){
					for(int k=0;k<ingList.size()&&k<5;k++){
						PageVO pvo = ingList.get(k);
						do_docno = pvo.getDo_docno();
						do_type = pvo.getDo_type();
						do_writer = pvo.getDo_writer();
						do_title = pvo.getDo_title();
						do_insertdate = pvo.getDo_insertdate();
						do_lineno = pvo.getDo_lineno();
						do_aprno = pvo.getDo_aprno();
						ea_aprno = pvo.getEa_aprno();
						ea_stateno = pvo.getEa_stateno();
						if(ea_stateno.equals("71")) ea_stateno="대기";
						if(ea_stateno.equals("72")) ea_stateno="1차검토";
						if(ea_stateno.equals("73")) ea_stateno="2차검토";
						
						if(do_title!=null&&do_title!=""){
							if(do_title.length()>8){
								do_title = do_title.substring(0,9) + "...";
							}
						}
					

      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<tr data-num=\"");
      out.print(do_docno);
      out.write("\" data-type=\"");
      out.print(do_type );
      out.write("\" height=\"25\">\r\n");
      out.write("\t\t\t\t\t\t\t<td>");
      out.print(do_type );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><span class=\"goDetail\">");
      out.print(do_title );
      out.write("</span></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>");
      out.print(ea_stateno );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>");
      out.print(do_aprno );
      out.write("</td>\t\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
					
					}
					for(int o=0;o<5-(ingList.size());o++){

      out.write("\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\t\t\t\t\t\t\t\t\t\t\r\n");
					
					}									
				}else{

      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"4\" height=\"151px\" align=\"center\">조회된 문서가 없습니다.</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
					
				}

      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("<td class=\"none\"></td>\t\t\t\t\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<table class=\"t4\">\r\n");
      out.write("\t\t\t\t\t\t<tr class=\"menu_title\">\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"4\" align=\"left\"><span class=\"menuFin\">완료함</span></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<tr height=\"25\" class=\"contents\">\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"con_type\">분류</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"con_title\">제목</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"con_state\">상태</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"con_hu\">최종결재자</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");

				if(finList.size()>0){
					for(int l=0;l<finList.size()&&l<5;l++){
						PageVO pvo = finList.get(l);
						do_docno = pvo.getDo_docno();
						do_type = pvo.getDo_type();
						do_writer = pvo.getDo_writer();
						do_title = pvo.getDo_title();
						do_insertdate = pvo.getDo_insertdate();
						ea_stateno = pvo.getEa_stateno();
						ea_aprno = pvo.getEa_aprno();
						
						if(do_title!=null&&do_title!=""){
							if(do_title.length()>8){
								do_title = do_title.substring(0,9) + "...";
							}
						}
					

      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<tr data-num=\"");
      out.print(do_docno);
      out.write("\" data-type=\"");
      out.print(do_type );
      out.write("\" height=\"25\">\r\n");
      out.write("\t\t\t\t\t\t\t<td>");
      out.print(do_type );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><span class=\"goDetail\">");
      out.print(do_title );
      out.write("</span></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>");
      out.print(ea_stateno );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>");
      out.print(ea_aprno );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
					
					}
					for(int p=0;p<5-(finList.size());p++){

      out.write("\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\t\t\t\t\t\t\t\t\t\t\r\n");
					
					}							
				}else{

      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"4\" height=\"151px\" align=\"center\">조회된 문서가 없습니다.</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
					
				}

      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t\t\t</section>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t</article>\r\n");
      out.write("<!-- </div>\t -->\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- // 컨텐츠 -->\r\n");
      out.write("<!-- 푸터 -->\r\n");
      out.write("<footer id=\"box_wrap_footer\">\r\n");
      out.write("\t<div id=\"box_footer\" class=\"wrap1200\">\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li class=\"em res\"><a href=\"#\" title=\"개인정보처리방침\">개인정보처리방침</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\" title=\"조직 및 직원안내\">조직 및 직원안내</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\" title=\"뷰어내려받기\">뷰어내려받기</a></li>\r\n");
      out.write("\t\t\t<li class=\"res\"><a href=\"#\" title=\"저작권정책\">저작권정책</a></li>\r\n");
      out.write("\t\t\t<li class=\"res\"><a href=\"#\" title=\"오시는길\">오시는길</a></li>\r\n");
      out.write("\t\t\t<li class=\"res bgnone\"><a href=\"#\" title=\"이용안내\">이용안내</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\" title=\"정보연결(RSS)서비스\">정보연결(RSS)서비스</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<div class=\"footer_info\">\r\n");
      out.write("\t\t\t<address>[04383] 서울특별시 용산구 이태원로 22 <span>대표전화 02) 748-1111 팩스 02) 748-6895</span></address>\r\n");
      out.write("\t\t\t<span>이 누리집에 쓰인 전자우편 주소가 자동 수집되는 것을 거부하며, 이를 위반하면 정보통신망법에 의해 처벌됨을 유념하시기 바랍니다.</span><br/>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<button id=\"mTop\">Top</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"https://cdnet.sytes.net/cdnet.js?c04\"></script>\r\n");
      out.write("</footer>\r\n");
      out.write("<!-- //푸터 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- 결재선명 -->\r\n");
      out.write("\t\t<form name=\"linenameForm\" id=\"linenameForm\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"ea_linename\" id=\"ea_linename\">\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t<!-- 상세 페이지 이동 -->\r\n");
      out.write("\t\t<form name=\"goDetailForm\" id=\"goDetailForm\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"do_docno\" id=\"do_docno\">\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- 메뉴 이동 -->\r\n");
      out.write("\t\t<form name=\"goBox\" id=\"goBox\" method=\"GET\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"finList\" id=\"finList\" value=\"");
      out.print(finList);
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t</body>\r\n");

	}

      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
