/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.12
 * Generated at: 2021-03-30 16:24:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.ea;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.File;
import java.util.ArrayList;
import java.util.Collection;

public final class paging_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\t\t\r\n");

	/**********************************
	전달해야 할 변수
	***********************************/
	String	url = null;
	String	str = null;
	
	url = request.getParameter("url");
	str = request.getParameter("str");

	if(str != null)
	{
		str = str + "&";
	}

      out.write("\r\n");
      out.write("\r\n");

	/**********************************
	페이지 네비게이션 관련 변수
	***********************************/
	// 한페이지에 보여질 게시물의 수
	int pageSize = 10;
	
	// 그룹의 크기
	int groupSize = 10;
	
	// 전체 게시물의 개수
	int totalCount = 0;
	
	//현재 페이지
	int curPage = 0;
	
	// 전체 페이지의 개수
	int pageCount = 0;
	
	
	if(request.getParameter("curPage1") != null)
	{
		curPage = Integer.parseInt(request.getParameter("curPage1"));
	}
	
	if(request.getParameter("totalCount") != null)
	{
		totalCount = Integer.parseInt(request.getParameter("totalCount"));
	}
	
	// 전체게시물수와 페이지크기를 가지고 전체 페이지 개수를 계산함.
	// 소수점에 따라 계산상의 오류가 없도록 한것임.
	pageCount = (int)Math.ceil(totalCount / (pageSize+0.0));
	
	// 현재그룹 설정
	int curGroup = 0;
	if(curPage==1){
		curGroup = 0;
	}else{
		curGroup = (curPage-1) / groupSize;
	}
	int linkPage = curGroup * groupSize;

      out.write("\r\n");
      out.write("<p align=\"center\">\r\n");

	// 첫번째 그룹인 아닌경우
	if(curGroup > 0) {

      out.write("\r\n");
      out.write("\t<span class=\"btnFirst\"><a href=\"javascript:goPage(1)\">◀</a></span>&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t<span class=\"btnPrev\"><a href=\"javascript:goPage(");
      out.print(linkPage);
      out.write(")\">◁</a></span>&nbsp;&nbsp;&nbsp;\r\n");

	}
	else
	{

      out.write("\r\n");
      out.write("<span class=\"btnFirst\">◀</span>&nbsp;&nbsp;&nbsp;<span class=\"btnPrev\">◁</span>&nbsp;&nbsp;&nbsp;\r\n");

	}
	
	// 다음 링크를 위해 증가시킴
	linkPage++;

	int loopCount = groupSize;
	// 그룹범위내에서 페이지 링크만듬.
	while((loopCount > 0) && (linkPage <= pageCount))
	{
		if(linkPage == curPage)
		{

      out.write('\r');
      out.write('\n');
      out.write('	');
      out.print(linkPage);
      out.write(" \r\n");
      out.write("\r\n");

		}
		else
		{

      out.write("\r\n");
      out.write("\t[<a href=\"javascript:goPage(");
      out.print(linkPage);
      out.write(')');
      out.write('"');
      out.write('>');
      out.print(linkPage);
      out.write("</a>]&nbsp;\r\n");

		}
		
		linkPage++;
		loopCount--;
	}
	
	// 다음그룹이 있는 경우
	if(linkPage <= pageCount)
	{

      out.write("\r\n");
      out.write("\t<span class=\"btnNext\"><a href=\"javascript:goPage(");
      out.print(linkPage);
      out.write(")\">▷</a></span>&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t<span class=\"btnEnd\"><a href=\"javascript:goPage(");
      out.print(pageCount);
      out.write(")\">▶</a></span>&nbsp;&nbsp;&nbsp;\r\n");

	}
	else
	{

      out.write("\r\n");
      out.write("\t<span class=\"btnNext\">▷</span>&nbsp;&nbsp;&nbsp;<span class=\"btnEnd\">▶</span>&nbsp;&nbsp;&nbsp;\r\n");

	}

      out.write("\r\n");
      out.write("</p>\t\t\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
