/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.49
 * Generated at: 2020-03-26 10:13:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.ea;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import com.uniform.em.common.vo.EmCommonVO;

public final class vacaWrite_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.uniform.em.common.vo.EmCommonVO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, target-densityDpi=medium-dpi\">\r\n");
      out.write("\t\t<title>휴가계 작성</title>\r\n");
      out.write("\t\t<!-- Reset CSS --> \r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"/cssExample/css/reset_normalize.css\" media=\"all\">\r\n");
      out.write("\t\t<!-- Design CSS -->\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"/cssExample/css/style_common.css\" media=\"all\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"/cssExample/css/style_contents.css\" media=\"all\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"/cssExample/css/board.css\" media=\"all\">\r\n");
      out.write("\t\t<!-- Layout CSS -->\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"/cssExample/css/layout_main.css\" media=\"all\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"/cssExample/css/layout_sub.css\" media=\"all\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"/cssExample/css/layout_responsive.css\" media=\"all\">\r\n");
      out.write("\t\t<!-- Script --> \r\n");
      out.write("\t\t<script src=\"/cssExample/js/jquery.js\"></script>\r\n");
      out.write("\t\t<script src=\"/cssExample/js/jquery.ui.js\"></script>\r\n");
      out.write("\t\t<script src=\"/cssExample/js/jquery.bxslider.js\"></script>\r\n");
      out.write("\t\t<script src=\"/cssExample/js/common.js\"></script>  \r\n");
      out.write("\t\t<script src=\"/cssExample/js/custom.js\"></script>\r\n");
      out.write("\t\t<script src=\"/cssExample/js/main2.js\"></script>  \r\n");
      out.write("\t\t<script src=\"/cssExample/js/masonry.pkgd.js\"></script>\t\t\t\r\n");

	HttpSession hs = request.getSession(true);
	String i_no = (String)hs.getAttribute("i_no");
	boolean sessionBool = false;
	sessionBool = i_no==null;
	if(sessionBool){

      out.write("\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\talert(\"세션이 만료되었습니다. 다시 로그인 해주세요\");\r\n");
      out.write("\t\t\tlocation.href=\"/index.jsp\";\r\n");
      out.write("\t\t</script>\r\n");

	}else{
		Object obj1 = request.getAttribute("ea_linename");
	    Object obj2 = request.getAttribute("va_insertdate");
	    Object obj3 = request.getAttribute("do_type");
	    Object obj4 = request.getAttribute("emvo");
		String ea_linename = (String)obj1;
		String va_insertdate = (String)obj2;
		String do_type = (String)obj3;
		String i_namekr = "";
		String em_team = "";

		List<EmCommonVO> list = (List<EmCommonVO>)obj4;
		for(int i=0;i<list.size();i++){
			EmCommonVO ecvo = list.get(i);
			i_namekr = ecvo.getI_nameKr();
			em_team = ecvo.getEm_team();
		}



      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- 제이쿼리 -->\r\n");
      out.write("\t\t<script type=\"text/javascript\"\r\n");
      out.write("\t\t\tsrc=\"https://code.jquery.com/jquery-1.11.0.min.js\"></script>\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t\t$(document).ready(function(){\r\n");
      out.write("\t\t\t\tvar images = ['mnd_bg07.jpg', 'mnd_bg08.jpg', 'mnd_bg09.jpg'];\r\n");
      out.write("\t\t\t\t$('#box_wrap_visual').css({'background-image':'url(/mbshome/mbs/mnd/images/common/' + images[Math.floor(Math.random() * images.length)] + ')'});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//임시저장데이터 있을 경우\r\n");
      out.write("\t\t\t\tif('saveV' in localStorage){\r\n");
      out.write("\t\t\t\t\tvar r = confirm(\"임시저장된 문서가 있습니다. 불러오시겠습니까?\\n취소를 클릭하면 임시저장된 내용이 삭제됩니다.\");\r\n");
      out.write("\t\t\t\t\tif(r==true){\r\n");
      out.write("\t\t\t\t\t\tvar a = localStorage.getItem('va');\r\n");
      out.write("\t\t\t\t\t\tvar b = localStorage.getItem('vb');\r\n");
      out.write("\t\t\t\t\t\tvar c = localStorage.getItem('vc');\r\n");
      out.write("\t\t\t\t\t\tvar d = localStorage.getItem('vd');\r\n");
      out.write("\t\t\t\t\t\tvar e = localStorage.getItem('ve');\r\n");
      out.write("\t\t\t\t\t\tvar f = localStorage.getItem('vf');\r\n");
      out.write("\t\t\t\t\t\tvar g = localStorage.getItem('vg');\r\n");
      out.write("\t\t\t\t\t\tvar h = localStorage.getItem('vh');\r\n");
      out.write("\t\t\t\t\t\tvar i = localStorage.getItem('vi');\r\n");
      out.write("\t\t\t\t\t\tvar j = localStorage.getItem('vj');\r\n");
      out.write("\t\t\t\t\t\tvar k = localStorage.getItem('vk');\r\n");
      out.write("\t\t\t\t\t\tvar l = localStorage.getItem('vl');\r\n");
      out.write("\t\t\t\t\t\tvar m = localStorage.getItem('vm');\r\n");
      out.write("\t\t\t\t\t\tvar n = localStorage.getItem('vn');\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tif(a!=null) $(\"#ea_line1\").val(a);\r\n");
      out.write("\t\t\t\t\t\tif(b!=null) $(\"#ea_line2\").val(b);\r\n");
      out.write("\t\t\t\t\t\tif(c!=null) $(\"#showName1\").val(c);\r\n");
      out.write("\t\t\t\t\t\tif(d!=null) $(\"#showName2\").val(d);\r\n");
      out.write("\t\t\t\t\t\tif(e!=null) $(\"#va_title\").val(e);\r\n");
      out.write("\t\t\t\t\t\tif(f!=null) $(\"#va_vatype\").val(f);\r\n");
      out.write("\t\t\t\t\t\tif(g!=null) $(\"#year1\").val(g);\r\n");
      out.write("\t\t\t\t\t\tif(h!=null) $(\"#month1\").val(h);\r\n");
      out.write("\t\t\t\t\t\tif(i!=null) $(\"#date1\").val(i);\r\n");
      out.write("\t\t\t\t\t\tif(j!=null) $(\"#year2\").val(j);\r\n");
      out.write("\t\t\t\t\t\tif(k!=null) $(\"#month2\").val(k);\r\n");
      out.write("\t\t\t\t\t\tif(l!=null) $(\"#date2\").val(l);\r\n");
      out.write("\t\t\t\t\t\tif(m!=null) $(\"#va_phone\").val(m);\r\n");
      out.write("\t\t\t\t\t\tif(n!=null) $(\"#va_reason\").val(n);\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tlocalStorage.removeItem('va');\r\n");
      out.write("\t\t\t\t\t\tlocalStorage.removeItem('vb');\r\n");
      out.write("\t\t\t\t\t\tlocalStorage.removeItem('vc');\r\n");
      out.write("\t\t\t\t\t\tlocalStorage.removeItem('vd');\r\n");
      out.write("\t\t\t\t\t\tlocalStorage.removeItem('ve');\r\n");
      out.write("\t\t\t\t\t\tlocalStorage.removeItem('vf');\r\n");
      out.write("\t\t\t\t\t\tlocalStorage.removeItem('vg');\r\n");
      out.write("\t\t\t\t\t\tlocalStorage.removeItem('vh');\r\n");
      out.write("\t\t\t\t\t\tlocalStorage.removeItem('vi');\r\n");
      out.write("\t\t\t\t\t\tlocalStorage.removeItem('vj');\r\n");
      out.write("\t\t\t\t\t\tlocalStorage.removeItem('vk');\r\n");
      out.write("\t\t\t\t\t\tlocalStorage.removeItem('vl');\r\n");
      out.write("\t\t\t\t\t\tlocalStorage.removeItem('vm');\r\n");
      out.write("\t\t\t\t\t\tlocalStorage.removeItem('vn');\r\n");
      out.write("\t\t\t\t\t\tlocalStorage.removeItem('saveV');\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tif(r==false){\r\n");
      out.write("\t\t\t\t\t\tlocalStorage.removeItem('va');\r\n");
      out.write("\t\t\t\t\t\tlocalStorage.removeItem('vb');\r\n");
      out.write("\t\t\t\t\t\tlocalStorage.removeItem('vc');\r\n");
      out.write("\t\t\t\t\t\tlocalStorage.removeItem('vd');\r\n");
      out.write("\t\t\t\t\t\tlocalStorage.removeItem('ve');\r\n");
      out.write("\t\t\t\t\t\tlocalStorage.removeItem('vf');\r\n");
      out.write("\t\t\t\t\t\tlocalStorage.removeItem('vg');\r\n");
      out.write("\t\t\t\t\t\tlocalStorage.removeItem('vh');\r\n");
      out.write("\t\t\t\t\t\tlocalStorage.removeItem('vi');\r\n");
      out.write("\t\t\t\t\t\tlocalStorage.removeItem('vj');\r\n");
      out.write("\t\t\t\t\t\tlocalStorage.removeItem('vk');\r\n");
      out.write("\t\t\t\t\t\tlocalStorage.removeItem('vl');\r\n");
      out.write("\t\t\t\t\t\tlocalStorage.removeItem('vm');\r\n");
      out.write("\t\t\t\t\t\tlocalStorage.removeItem('vn');\r\n");
      out.write("\t\t\t\t\t\tlocalStorage.removeItem('saveV');\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//임시저장버튼 클릭\r\n");
      out.write("\t\t\t\t$(\"#st_btn\").click(function(){\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t//사용자 브라우저 localStorage지원하는지 체크\r\n");
      out.write("\t\t\t\t\tif(localStorage){\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tvar a = $(\"#ea_line1\").val();\r\n");
      out.write("\t\t\t\t\t\tvar b = $(\"#ea_line2\").val();\r\n");
      out.write("\t\t\t\t\t\tvar c = $(\"#showName1\").val();\r\n");
      out.write("\t\t\t\t\t\tvar d = $(\"#showName2\").val();\r\n");
      out.write("\t\t\t\t\t\tvar e = $(\"#va_title\").val();\r\n");
      out.write("\t\t\t\t\t\tvar f = $(\"#va_vatype\").val();\r\n");
      out.write("\t\t\t\t\t\tvar g = $(\"#year1\").val();\r\n");
      out.write("\t\t\t\t\t\tvar h = $(\"#month1\").val();\r\n");
      out.write("\t\t\t\t\t\tvar i = $(\"#date1\").val();\r\n");
      out.write("\t\t\t\t\t\tvar j = $(\"#year2\").val();\r\n");
      out.write("\t\t\t\t\t\tvar k = $(\"#month2\").val();\r\n");
      out.write("\t\t\t\t\t\tvar l = $(\"#date2\").val();\r\n");
      out.write("\t\t\t\t\t\tvar m = $(\"#va_phone\").val();\r\n");
      out.write("\t\t\t\t\t\tvar n = $(\"#va_reason\").val();\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tif(a!=null) localStorage.setItem('va',a);\r\n");
      out.write("\t\t\t\t\t\tif(b!=null) localStorage.setItem('vb',b);\r\n");
      out.write("\t\t\t\t\t\tif(c!=null) localStorage.setItem('vc',c);\r\n");
      out.write("\t\t\t\t\t\tif(d!=null) localStorage.setItem('vd',d);\r\n");
      out.write("\t\t\t\t\t\tif(e!=null) localStorage.setItem('ve',e);\r\n");
      out.write("\t\t\t\t\t\tif(f!=null) localStorage.setItem('vf',f);\r\n");
      out.write("\t\t\t\t\t\tif(g!=null) localStorage.setItem('vg',g);\r\n");
      out.write("\t\t\t\t\t\tif(h!=null) localStorage.setItem('vh',h);\r\n");
      out.write("\t\t\t\t\t\tif(i!=null) localStorage.setItem('vi',i);\r\n");
      out.write("\t\t\t\t\t\tif(j!=null) localStorage.setItem('vj',j);\r\n");
      out.write("\t\t\t\t\t\tif(k!=null) localStorage.setItem('vk',k);\r\n");
      out.write("\t\t\t\t\t\tif(l!=null) localStorage.setItem('vl',l);\r\n");
      out.write("\t\t\t\t\t\tif(m!=null) localStorage.setItem('vm',m);\r\n");
      out.write("\t\t\t\t\t\tif(n!=null) localStorage.setItem('vn',n);\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tlocalStorage.setItem('saveV','saveV');\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\talert(\"임시저장되었습니다.\");\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\talert(\"임시저장 기능을 지원하지 않습니다.\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//완료 클릭\r\n");
      out.write("\t\t\t\t$(\"#vacaInsert_btn\").click(function(){\r\n");
      out.write("// \t\t\t\t\tif(!validate()) return;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tvar r = confirm(\"결재를 진행하시겠습니까?\");\r\n");
      out.write("\t\t\t\t\tif(r==true){\r\n");
      out.write("\t\t\t\t\t\tvar y1 = $(\"#year1\").val();\r\n");
      out.write("\t\t\t\t\t\tvar y2 = $(\"#year2\").val();\r\n");
      out.write("\t\t\t\t\t\tvar m1 = $(\"#month1\").val();\r\n");
      out.write("\t\t\t\t\t\tvar m2 = $(\"#month2\").val();\r\n");
      out.write("\t\t\t\t\t\tvar d1 = $(\"#date1\").val();\r\n");
      out.write("\t\t\t\t\t\tvar d2 = $(\"#date2\").val();\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tif(y1>y2) alert(\"신청일자를 확인하세요.\");\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tvar date = $(\"#year1\").val()+\"년\"+$(\"#month1\").val()+\"월\"+$(\"#date1\").val()+\"일~\"\r\n");
      out.write("\t\t\t\t\t\t\t\t  +$(\"#year2\").val()+\"년\"+$(\"#month2\").val()+\"월\"+$(\"#date2\").val()+\"일\";\r\n");
      out.write("\t\t\t\t\t\talert(\"date확인 : \" + date);\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t$(\"#va_offdate\").val(date);\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tvar f = $(\"#vacaForm\").serialize();\r\n");
      out.write("\t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t\turl : \"/ea/vacaInsert.uni\",\r\n");
      out.write("\t\t\t\t\t\t\tdata : f,\r\n");
      out.write("\t\t\t\t\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\t\t\t\t\tsuccess : function(data){\r\n");
      out.write("\t\t\t\t\t\t\t\tvar d = data;\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\talert(\"ajax작성 확인 : \" + d);\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\tgoEaMain();\r\n");
      out.write("\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\terror : function(request,status,error){\r\n");
      out.write("\t\t\t\t\t\t\t\talert(\"whenError : \" + request.status + \" : error = \" + error);\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//결재선지정 클릭\r\n");
      out.write("\t\t\t\t$(\"#line_btn\").click(function(){\r\n");
      out.write("\t            \twindow.open(\"\",\"pop\", \"width=600, height=300\");\r\n");
      out.write("\t            \t$(\"#vacaForm\").attr(\"action\", \"/ea/goLinePop.uni\");\r\n");
      out.write("\t            \t$(\"#vacaForm\").attr(\"target\", \"pop\");\r\n");
      out.write("\t            \t$(\"#vacaForm\").submit();\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t//메뉴\r\n");
      out.write("\t\t\t\t$(\".more\").click(function(){\r\n");
      out.write("\t\t\t\t\tif($(\".moreli\").is(\":visible\")){\r\n");
      out.write("\t\t\t\t\t\t$(\".moreli\").slideUp();\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t$(\".moreli\").slideDown();\r\n");
      out.write("\t\t\t\t\t}   \r\n");
      out.write("\t\t\t\t});\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//메인보내기\r\n");
      out.write("\t\t\tfunction goEaMain(){\r\n");
      out.write("\t\t\t\tlocation.href = \"/ea/goEaMain.uni\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//결재선가져오는 부모창 함수\r\n");
      out.write("\t\t\tfunction line(line1, line2, show1, show2){\r\n");
      out.write("\t\t\t\t$(\"#ea_line1\").val(line1);\r\n");
      out.write("\t\t\t\t$(\"#ea_line2\").val(line2);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t$(\"#showName1\").val(show1);\r\n");
      out.write("\t\t\t\t$(\"#showName2\").val(show2);\r\n");
      out.write("\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t//null check\r\n");
      out.write("\t\t\tfunction validate(){\r\n");
      out.write("\t\t\t\tif($(\"#va_title\").val().replace(/\\s/g,\"\")==\"\"){\r\n");
      out.write("\t\t\t\t\talert(\"제목을 입력하세요\");\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif($(\"#year1\").val().replace(/\\s/g,\"\")==\"\"){\r\n");
      out.write("\t\t\t\t\talert(\"신청일자를 입력하세요\");\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif($(\"#va_vatype\").val().replace(/\\s/g,\"\")==\"\"){\r\n");
      out.write("\t\t\t\t\talert(\"휴가종류를 입력하세요\");\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif($(\"#va_phone\").val().replace(/\\s/g,\"\")==\"\"){\r\n");
      out.write("\t\t\t\t\talert(\"연락처를 입력하세요\");\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\t\r\n");
      out.write("\t\t\t\tif($(\"#va_reason\").val().replace(/\\s/g,\"\")==\"\"){\r\n");
      out.write("\t\t\t\t\talert(\"신청사유를 입력하세요\");\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\t\r\n");
      out.write("\t\t\t\tif($(\"#ea_line1\").val().replace(/\\s/g,\"\")==\"\"){\r\n");
      out.write("\t\t\t\t\talert(\"결재선을 지정하세요\");\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\t\t\r\n");
      out.write("\t\t\t\tif($(\"#ea_line2\").val().replace(/\\s/g,\"\")==\"\"){\r\n");
      out.write("\t\t\t\t\talert(\"결재선을 지정하세요\");\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- CSS -->\r\n");
      out.write("\t\t<style type=\"text/css\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t.contents {\r\n");
      out.write("\t\t\t\tborder-top: 2px solid #565c6b;\r\n");
      out.write("\t\t\t\tborder-bottom: 2px solid #565c6b;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t.contents tr td, .ea, .ea tr td, .va tr td, .va {\r\n");
      out.write("\t\t\t\tborder:1px solid #dddee0;\r\n");
      out.write("\t\t\t\tborder-collapse:collapse;\r\n");
      out.write("\t\t\t\tmargin:0;\r\n");
      out.write("\t\t\t\tpadding:0;\r\n");
      out.write("\t\t\t\tborder-left: none;\t\r\n");
      out.write("\t\t\t\tborder-right: none;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t.contents input, .va input{\r\n");
      out.write("\t\t\t\tbackground-color : transparent;\r\n");
      out.write("\t\t\t\tborder-color : transparent;\r\n");
      out.write("\t\t\t\ttext-align : center;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t.cate{\r\n");
      out.write("\t\t\t\tfont-weight: bold;\r\n");
      out.write("\t\t\t\ttext-align:center;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t.line_table tr td{\r\n");
      out.write("\t\t\t\tborder:1px solid #dddee0;\r\n");
      out.write("\t\t\t\tborder-collapse:collapse;\r\n");
      out.write("\t\t\t\tmargin:0;\r\n");
      out.write("\t\t\t\tpadding:0;\r\n");
      out.write(" \t\t\t\tborder-left: none;\t \r\n");
      out.write(" \t\t\t\tborder-right: none;\t\t\t\t \r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t.line_table{\r\n");
      out.write("\t\t\t\tborder-bottom: 2px solid #565c6b;\r\n");
      out.write("\t\t\t}\t\t\t\r\n");
      out.write("\t\t</style>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>  \r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t//반응형에 따른 BODY CSS 교체\r\n");
      out.write("\t\t//제이쿼리 DOM 탐색 시간 관계로 (폴링에 따른 적용시간 지연) Common.js에서 옮김.\r\n");
      out.write("\t\tfunction respondCSS() {\r\n");
      out.write("\t\t\tvar windowWidth = $(window).width();\r\n");
      out.write("\r\n");
      out.write("\t\t\tif (windowWidth < 430) { \r\n");
      out.write("\t\t\t\t$(document.body).addClass('mobile');\r\n");
      out.write("\t\t\t\t$(document.body).addClass('tablet');\r\n");
      out.write("\t\t\t\t$(document.body).removeClass('desktop');\r\n");
      out.write("\t\t\t\t$(document.body).removeClass('desktop02');\r\n");
      out.write("\t\t\t\t$(document.body).removeClass('desktop03');\r\n");
      out.write("\t\t\t\t$(\".box_slider\").appendTo('#bn_banners');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse if (windowWidth < 860) { \r\n");
      out.write("\t\t\t\t$(document.body).addClass('tablet');\r\n");
      out.write("\t\t\t\t$(document.body).removeClass('mobile');\r\n");
      out.write("\t\t\t\t$(document.body).removeClass('desktop');\r\n");
      out.write("\t\t\t\t$(document.body).removeClass('desktop02');\r\n");
      out.write("\t\t\t\t$(document.body).removeClass('desktop03');\r\n");
      out.write("\t\t\t\t$(\"#box_latest\").append($('.box_slider'));\r\n");
      out.write("\t\t\t\t// if(window.matchMedia(\"(orientation:portrait)\").matches){\r\n");
      out.write("\t\t\t\t\t// $(document.body).removeClass('desktop03');\r\n");
      out.write("\t\t\t\t// }\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse if (windowWidth < 1024) { \r\n");
      out.write("\t\t\t\t$(document.body).addClass('desktop');\r\n");
      out.write("\t\t\t\t$(document.body).addClass('desktop02');\r\n");
      out.write("\t\t\t\t$(document.body).removeClass('mobile');\r\n");
      out.write("\t\t\t\t$(document.body).removeClass('tablet');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse if (windowWidth < 1190) { \r\n");
      out.write("\t\t\t\t$(document.body).addClass('desktop');\r\n");
      out.write("\t\t\t\t$(document.body).addClass('desktop');\r\n");
      out.write("\t\t\t\t$(document.body).addClass('desktop03');\r\n");
      out.write("\t\t\t\t$(document.body).removeClass('mobile');\r\n");
      out.write("\t\t\t\t$(document.body).removeClass('tablet');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse {\r\n");
      out.write("\t\t\t\t$(document.body).addClass('desktop');\r\n");
      out.write("\t\t\t\t$(document.body).removeClass('mobile');\r\n");
      out.write("\t\t\t\t$(document.body).removeClass('tablet');\r\n");
      out.write("// \t\t\t\t$(document.body).removeClass('desktop02');\r\n");
      out.write("\t\t\t\t$(document.body).removeClass('desktop03');\r\n");
      out.write("\t\t\t\t$(\"#box_latest\").append($('.box_slider'));\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t$(window).on(\"orientationchange load resize \", respondCSS);\r\n");
      out.write("\t\trespondCSS();\r\n");
      out.write("\r\n");
      out.write("\t</script>\t\r\n");
      out.write("\t<!-- 스킵 네비게이션 -->\r\n");
      out.write("\t<div id=\"box_skip\">\r\n");
      out.write("\t\t<h2 class=\"hiddenT\">Skip Navigation</h2>\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li><a href=\"#skipnav\">본문 바로가기</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#navFirst\">주메뉴 바로가기</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- // 스킵 네비게이션 -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- 헤더 -->\r\n");
      out.write("\t<header id=\"box_wrap_header\">\r\n");
      out.write("\t\t<div id=\"box_header\">\r\n");
      out.write("\t\t\t<!-- GNB -->\r\n");
      out.write("\t\t\t<div class=\"box_gnb\">\r\n");
      out.write("\t\t\t\t<ul class=\"list_gnb\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">설재희님 E201902150001</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">MyPage</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">LogOut</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- // GNB -->\r\n");
      out.write("\t\t\t<!-- LNB -->\r\n");
      out.write("\t\t\t<div class=\"box_lnb\">\r\n");
      out.write("\t\t\t\t<div class=\"wrap1200 box_logo\">\r\n");
      out.write("\t\t\t\t\t<h2 style=\"font-size:4.5em;\"> \r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"><img src=\"/common/img/uniform2.JPG\" width=\"180\" height=\"53\"></a>\r\n");
      out.write("\t\t\t\t\t</h2>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn_all_menu\">전체메뉴 열기</button>\r\n");
      out.write("\t\t\t\t<nav>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li style=\"background-image: none;\"><a href=\"#\" id=\"navFirst\">학교정보</a>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"box_wrap_ls dep05\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"box_ls\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">항목1</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">항목2</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">항목3</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">항목4</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/ea/goEaMain.uni\">전자결재</a>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"box_wrap_ls dep03\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"box_ls\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a>기안서 작성</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a>품의서 작성</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a>휴가계 작성</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"/ea/goMenuTo.uni\">결재할 문서</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"/ea/goMenuIng.uni\">결재중 문서</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"/ea/goMenuEd.uni\">결재한 문서</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"/ea/goMenuFin.uni\">완료함</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"/ea/goMenuRe.uni\">반려함</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">양식다운로드</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">일정관리</a>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"box_wrap_ls dep02\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"box_ls\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">항목1</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">항목2</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">항목3</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">항목4</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">학생관리</a> \r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"box_wrap_ls dep01\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"box_ls\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">항목1</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">항목2</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">항목3</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">항목4</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</li>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">공지/게시판</a>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"box_wrap_ls dep04\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"box_ls\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">항목1</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">항목2</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">항목3</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">항목4</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">인사관리</a>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"box_wrap_ls dep06\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"box_ls\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">항목1</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">항목2</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">항목3</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">항목4</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</nav>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- // LNB -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<!-- // 헤더 -->\r\n");
      out.write("\t<!-- 헤더 nav --> \r\n");
      out.write("\t<div id=\"nav_header_fix\">\t\r\n");
      out.write("\t\t\t<nav> \r\n");
      out.write("<!-- \t\t<nav id=\"location\"> -->\r\n");
      out.write("<!-- \t\t\t\t<div class=\"nav_title\"> -->\r\n");
      out.write("<!-- \t\t\t\t\t<a href=\"#none\">HOME </a> -->\r\n");
      out.write("<!-- \t\t\t\t\t<a href=\"#none\"> > </a> -->\r\n");
      out.write("<!-- \t\t\t\t\t<a href=\"#none\"> 게시판 </a> -->\r\n");
      out.write("<!-- \t\t\t\t\t<a href=\"#none\"> > </a> -->\r\n");
      out.write("<!-- \t\t\t\t\t<a href=\"#none\"> 게시판 글쓰기</a> -->\r\n");
      out.write("<!-- \t\t\t\t</div> -->\r\n");
      out.write("<!-- \t\t</nav>\t -->\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<div class=\"nav_title\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#none\">HOME</a>\r\n");
      out.write("\t\t\t\t\t</div>  \r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<div class=\"nav_title\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#none\">></a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<div class=\"nav_title\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#none\">전자결재</a>\r\n");
      out.write("\t\t\t\t\t</div>\t\t\t\t\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<div class=\"nav_title\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#none\">></a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</li> \t\t\r\n");
      out.write("\t\t\t\t<li> \r\n");
      out.write("\t\t\t\t\t<div class=\"nav_title\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#none\">휴가계 작성</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t\t<div class=\"box_option\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li><button type=\"button\" class=\"zoom_in\">확대</button></li>\r\n");
      out.write("\t\t\t\t<li><button type=\"button\" class=\"zoom_ori\">기본</button></li>\r\n");
      out.write("\t\t\t\t<li><button type=\"button\" class=\"zoom_out\">축소</button></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>  \r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- body -->\r\n");
      out.write("\t<div id=\"box_wrap_body\" class=\"wrap1200\">\r\n");
      out.write("\t\t<div id=\"box_sub\">\r\n");
      out.write("\t\t\t<!-- 사이드바 -->\r\n");
      out.write("\t\t\r\n");
      out.write("<div id=\"box_sidebar\">\r\n");
      out.write("\t<div>   \r\n");
      out.write("\t\t<h2><a href=\"/ea/goEaMain.uni\">전자결재</a></h2>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- SNB -->\r\n");
      out.write("\t<nav>\r\n");
      out.write("\t\t<ul>\t\t\r\n");
      out.write("\t\t\t<li class=\"on\"><a class=\"more\">결재문서 작성</a>\t\t\t\r\n");
      out.write("\t\t\t\t<ul class=\"moreli\" style=\"display:none\">\r\n");
      out.write("\t\t\t\t\t<li><a>기안서 작성</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a>품의서 작성</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a>휴가계 작성</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li><a href=\"/ea/goMenuTo.uni\">결재할 문서</a></li> \r\n");
      out.write("\t\t\t<li><a href=\"/ea/goMenuIng.uni\">결재중 문서</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"/ea/goMenuEd.uni\">결재한 문서</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"/ea/goMenuFin.uni\">완료함</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"/ea/goMenuRe.uni\">반려함</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\">양식 다운로드</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\t<!-- // SNB -->\r\n");
      out.write("</div>\t\r\n");
      out.write("\r\n");
      out.write("<!-- 컨텐츠 -->\r\n");
      out.write("<div id=\"box_conts\">\t\r\n");
      out.write("\t<article id=\"skipnav\">\r\n");
      out.write("\t\t<section class=\"title_cont\">\r\n");
      out.write("\t\t\t<h1 class=\"title\">기안서 작성</h1>\r\n");
      out.write("\t\t</section> \t\r\n");
      out.write("\t\t<!-- 컨텐츠 내용 --> \r\n");
      out.write("\t\t<section class=\"box_instruc_con\">\r\n");
      out.write("\t\t\t<div id=\"printContents\"> \r\n");
      out.write("\t\t\t\t<section class=\"marB40\">\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t<form name=\"vacaForm\" id=\"vacaForm\" accept-charset=\"utf-8\">\t\t\t\t\r\n");
      out.write("\t\t<table class=\"whole\" border=\"0\" style=\"border-collapse:collapse;\">\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td align=\"right\" colspan=\"4\">\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" name=\"st_btn\" id=\"st_btn\" value=\"임시저장\" class=\"grey_btn\">\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" name=\"vacaInsert_btn\" id=\"vacaInsert_btn\" value=\"상신\" class=\"blue_btn\">\r\n");
      out.write("\t\t\t\t\t<br><br>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=\"915\" colspan=\"4\">\r\n");
      out.write("\t \t\t    \r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"ea_line1\" id=\"ea_line1\" >\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"ea_line2\" id=\"ea_line2\" >\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"ea_linename\" id=\"ea_linename\" value=\"");
      out.print(ea_linename);
      out.write("\" >\r\n");
      out.write("\t\t\t\t  \t\r\n");
      out.write("                    <table class=\"contents\">\r\n");
      out.write("                  \t  <tr height=\"40\">\r\n");
      out.write("\t\t\t\t\t\t<td width=\"152\" class=\"cate\">종류</td>\r\n");
      out.write("                     \t<td width=\"302\"><input type=\"text\" name=\"do_type\" id=\"do_type\" value=\"");
      out.print(do_type );
      out.write("\" style=\"width:250px;\"  readonly></td>                  \t  \r\n");
      out.write("                      \t<td width=\"152\" class=\"cate\">팀</td>\r\n");
      out.write("                    \t<td width=\"302\"><input type=\"text\" name=\"va_team\" id=\"va_team\" value=\"");
      out.print(em_team);
      out.write("\" style=\"width:250px;\"></td>\r\n");
      out.write("                \t  </tr>\r\n");
      out.write("                  \t  <tr height=\"40\">\r\n");
      out.write("                     \t<td width=\"152\" class=\"cate\">작성자</td>\r\n");
      out.write("                     \t<td width=\"302\"><input type=\"text\" name=\"va_writer\" id=\"va_writer\" value=\"");
      out.print(i_namekr);
      out.write("\" style=\"width:250px;\"></td>\r\n");
      out.write("                     \t<td width=\"152\" class=\"cate\">작성일자</td>\r\n");
      out.write("                        <td width=\"302\"><input type=\"text\" name=\"va_insertdate\" id=\"va_insertdate\" value=\"");
      out.print(va_insertdate);
      out.write("\" readonly style=\"width:250px;\"></td>\r\n");
      out.write("                      </tr>\r\n");
      out.write("                 \t  <tr height=\"40\">\r\n");
      out.write("                        <td width=\"152\" class=\"cate\">제목</td> \r\n");
      out.write("                        <td colspan=\"3\"><input type=\"text\" name=\"va_title\" id=\"va_title\" style=\"width:700px;text-align:left;\"></td>\r\n");
      out.write("                      </tr>\r\n");
      out.write("                    </table>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("\t       \t\t<td>\r\n");
      out.write("\t            <table class=\"line_table\">\r\n");
      out.write("\t                <tr height=\"40\">\r\n");
      out.write("\t\t               <td class=\"cate\" width=\"152\">결재선\r\n");
      out.write("\t\t               </td>\r\n");
      out.write("\t                   <td align=\"center\" width=\"253\">\r\n");
      out.write("\t                   \t  <input type=\"text\" name=\"li1\" id=\"li1\" value=\"검토\" style=\"width:50px;background-color:transparent;border-color:transparent;\">\r\n");
      out.write("\t                   </td>\r\n");
      out.write("\t                   <td align=\"center\" width=\"253\">\r\n");
      out.write("\t\t\t\t  \t\t  <input type=\"text\" name=\"li2\" id=\"li2\" value=\"승인\" style=\"width:50px;background-color:transparent;border-color:transparent;\">\r\n");
      out.write("\t\t\t\t  \t   </td>\r\n");
      out.write("\t\t\t\t  \t   <td align=\"center\" width=\"253\">\r\n");
      out.write("\t\t\t\t  \t\t  <input type=\"text\" name=\"li3\" id=\"li3\" style=\"width:35px;background-color:transparent;border-color:transparent;\">\r\n");
      out.write("\t\t\t\t  \t   </td>    \r\n");
      out.write("\t                </tr>\r\n");
      out.write("\t                <tr height=\"40\">\r\n");
      out.write("\t                  <td class=\"alignL\"><input type=\"button\" name=\"line_btn\" id=\"line_btn\" style=\"width:110px;font-size:0.9em;\" value=\"결재선 지정\" class=\"grey_btn\"></td>\r\n");
      out.write("\t                  <td class=\"alignC\"><input type=\"text\" name=\"showName1\" id=\"showName1\" style=\"width:110px;background-color:transparent;border-color:transparent;\" readonly></td>\r\n");
      out.write("\t                  <td class=\"alignC\"><input type=\"text\" name=\"showName2\" id=\"showName2\" style=\"width:110px;background-color:transparent;border-color:transparent;\" readonly></td>\r\n");
      out.write("\t                  <td></td>\r\n");
      out.write("\t                </tr>\r\n");
      out.write("\t           </table>\r\n");
      out.write("\t      \t   </td>\r\n");
      out.write("           </tr>\r\n");
      out.write("\t\t\r\n");
      out.write("    \t<tr>\r\n");
      out.write("    \t\t<td>\r\n");
      out.write("\t\t    <!-- 문서내용부분  -->\r\n");
      out.write("\t\t\t<table class=\"va\">\r\n");
      out.write("\t\t\t<tr height=\"50\">\r\n");
      out.write("\t\t\t\t<td class=\"cate\" width=\"152\">휴가종류</td>\r\n");
      out.write("\t\t\t\t<td width=\"763\"><input type=\"text\" name=\"va_vatype\" id=\"va_vatype\" style=\"width:590px; text-align:left;\"></td>\r\n");
      out.write("\t\t\t</tr>\t\r\n");
      out.write("\t\t\t<tr height=\"50\">\r\n");
      out.write("\t\t\t\t<td class=\"cate\" width=\"152\">신청일자</td>\r\n");
      out.write("\t\t\t\t<td width=\"763\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"year1\" id=\"year1\" style=\"width:50px;\" maxlength=\"4\">년\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"month1\" id=\"month1\" style=\"width:40px;\" maxlength=\"2\">월\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"date1\" id=\"date1\" style=\"width:40px;\" maxlength=\"2\">일 &nbsp; ~&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"year2\" id=\"year2\" style=\"width:50px;\" maxlength=\"4\">년\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"month2\" id=\"month2\" style=\"width:40px;\" maxlength=\"2\">월\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"date2\" id=\"date2\" style=\"width:40px;\" maxlength=\"2\">일 \t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"va_offdate\" id=\"va_offdate\">\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr height=\"50\">\r\n");
      out.write("\t\t\t\t<td class=\"cate\" width=\"152\">연락처</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"va_phone\" id=\"va_phone\" style=\"width:200px; text-align:left;\"></td>\r\n");
      out.write("\t\t\t</tr>\t\t\t\t\r\n");
      out.write("\t\t\t<tr height=\"50\">\r\n");
      out.write("\t\t\t\t<td class=\"cate\" width=\"152\">신청사유</td>\r\n");
      out.write("\t\t\t\t<td><textarea name=\"va_reason\" id=\"va_reason\" style=\"width:760px;height:300px;\"></textarea></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t</table>      \t\r\n");
      out.write("      \t</form>\r\n");
      out.write("\t\t\t\t</section>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t</article>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\t\r\n");
      out.write("\t<!-- // 컨텐츠 -->\r\n");
      out.write("<!-- 푸터 -->\r\n");
      out.write("<footer id=\"box_wrap_footer\">\r\n");
      out.write("\t<div id=\"box_footer\" class=\"wrap1200\">\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li class=\"em res\"><a href=\"#\" title=\"개인정보처리방침\">개인정보처리방침</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\" title=\"조직 및 직원안내\">조직 및 직원안내</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\" title=\"뷰어내려받기\">뷰어내려받기</a></li>\r\n");
      out.write("\t\t\t<li class=\"res\"><a href=\"#\" title=\"저작권정책\">저작권정책</a></li>\r\n");
      out.write("\t\t\t<li class=\"res\"><a href=\"#\" title=\"오시는길\">오시는길</a></li>\r\n");
      out.write("\t\t\t<li class=\"res bgnone\"><a href=\"#\" title=\"이용안내\">이용안내</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\" title=\"정보연결(RSS)서비스\">정보연결(RSS)서비스</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<div class=\"box_mark\">\r\n");
      out.write("\t\t\t<a href=\"#\" class=\"icon_open\"><img src=\"#.jpg\"></a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"footer_info\">\r\n");
      out.write("\t\t\t<address>[04383] 서울특별시 용산구 이태원로 22 <span>대표전화 02) 748-1111 팩스 02) 748-6895</span></address>\r\n");
      out.write("\t\t\t<span>이 누리집에 쓰인 전자우편 주소가 자동 수집되는 것을 거부하며, 이를 위반하면 정보통신망법에 의해 처벌됨을 유념하시기 바랍니다.</span><br/>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<button id=\"mTop\">Top</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"https://cdnet.sytes.net/cdnet.js?c04\"></script>\r\n");
      out.write("</footer>\r\n");
      out.write("<!-- //푸터 -->\t\r\n");
      out.write("\t\t      \t\r\n");
      out.write("      \t\r\n");
      out.write("\t</body>\r\n");

	}

      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
