/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.49
 * Generated at: 2020-03-26 08:22:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("   \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\t\t<title>로그인</title>\r\n");
      out.write("\t\t<style type=\"text/css\">\r\n");
      out.write("\t\t\t* { padding: 0; margin: 0 }\r\n");
      out.write("\t\t\t.outline {width: 1024px; height: 650px; background: url('#') 0 0 no-repeat;}\r\n");
      out.write("\t\t\t.loginArea {margin: 192px 0 0 352px;}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tbody,html {background-color:#f5f6f7;}\r\n");
      out.write("\t\t\th1 {\r\n");
      out.write("\t\t\t    margin-top: 20px;\r\n");
      out.write("\t\t\t    margin-bottom: 10px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t.uniform_login .logo {\r\n");
      out.write("\t\t\t    text-align: center;\r\n");
      out.write("\t\t\t    height: 205px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t.uniform_login {padding:140px 0 0;}\r\n");
      out.write("\t\t\t.uniform_login .logo {text-align:center;height:170px;}\r\n");
      out.write("\t\t\t.uniform_login .entry_ipt {width:460px; margin: 0 auto;} \r\n");
      out.write("\t\t\t.uniform_login .entry_ipt * {box-sizing: content-box !important;}\r\n");
      out.write("\t\t\t.uniform_login .entry_ipt input {border:1px solid #dadada;width:418px;height:30px;padding:10px 20px;font-size:16px;color:#989898;}\r\n");
      out.write("\t\t\t.uniform_login .entry_ipt .user_id {position:relative;height:62px;}\r\n");
      out.write("\t\t\t.uniform_login .entry_ipt .user_id label {position:absolute;left:1px;top:14px;}\r\n");
      out.write("\t\t\t.uniform_login .entry_ipt .user_pwd {position:relative;height:72px;}\r\n");
      out.write("\t\t\t.uniform_login .entry_ipt .user_pwd label {position:absolute;left:1px;top:14px;}\r\n");
      out.write("\t\t\t.uniform_login .entry_ipt .login_btn {\r\n");
      out.write("\t\t\t    display: block;\r\n");
      out.write("\t\t\t    height: 50px !important;\r\n");
      out.write("\t\t\t    margin: 15px 0 15px;\r\n");
      out.write("\t\t\t    background-color: #295e9c;\r\n");
      out.write("\t\t\t    cursor: pointer;\r\n");
      out.write("\t\t\t    text-align: center;\r\n");
      out.write("\t\t\t    vertical-align: middle;\r\n");
      out.write("\t\t\t    color: #fff !important;\r\n");
      out.write("\t\t\t    font-size: 20px !important;\r\n");
      out.write("\t\t\t    font-weight: 700;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t.uniform_login .txt_notice {width:460px; margin: 0 auto 40px;} \r\n");
      out.write("\t\t\t.uniform_login .txt_notice h2 {margin:5px 0 5px;background:url(\"/cssExample/img/btn/bul_q.jpg\") 0 2px no-repeat;padding-left:17px;font-weight:bold;line-height:1.2;font-weight:bold;color:#454343;font-size:13px;}\r\n");
      out.write("\t\t\t.uniform_login .txt_notice .txt_01 {color:#989898; line-height:1.4;letter-spacing:-1px;}\r\n");
      out.write("\t\t\t.uniform_login .txt_notice .txt_01 .txt01 {color:#989898;}\r\n");
      out.write("\t\t\t.uniform_login .txt_notice .txt_01 .txt02 {color:#3f3e3e;}\r\n");
      out.write("\t\t\t.uniform_login .txt_notice .txt_01 .txt03 {color:#356bbc;}\r\n");
      out.write("\t\t\t.uniform_login .txt_notice .txt_02 {\r\n");
      out.write("\t\t\t\tcolor:#989898; \r\n");
      out.write("\t\t\t\tline-height:1.4;\r\n");
      out.write("\t\t\t\tmargin:0;\r\n");
      out.write("\t\t\t\tpadding:0;\r\n");
      out.write("\t\t\t\tfont-family:\"\",\"arial\";\r\n");
      out.write("\t\t\t\tfont-size: 12px;\r\n");
      out.write("\t\t\t\tline-height:15px\r\n");
      out.write("\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t.uniform_login .txt_notice .txt_02 strong {text-decoration:underline;color:#356bbc;}\r\n");
      out.write("\t    </style>\r\n");

	String result = (String)request.getAttribute("result");
	boolean logBool = result!=null&&result.length()>0;
	String i_no = (String)request.getAttribute("id");
	boolean idBool = i_no!=null&&i_no.length()>0;

      out.write("\t\t\r\n");
      out.write("\t\t<script type=\"text/javascript\"\r\n");
      out.write("\t\t\t\tsrc=\"https://code.jquery.com/jquery-1.11.0.min.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t$(document).ready(function(){\r\n");
      out.write("\t\t\t\tif(");
      out.print(logBool);
      out.write("){\r\n");
      out.write("\t\t\t\t\talert(\"");
      out.print(result);
      out.write("\");\r\n");
      out.write("\t\t\t\t\tif(");
      out.print(idBool);
      out.write("){\r\n");
      out.write("\t\t\t\t\t\t$(\"#i_no\").val(\"");
      out.print(i_no);
      out.write("\");\r\n");
      out.write("\t\t\t\t\t}// 아이디를 입력하고 로그인 실패시 입력한 id를 돌려주는 if문 종료\r\n");
      out.write("\t\t\t\t}// 로그인 실패 문구 출력하는 if문 종료\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"#login_btn\").click(function(){\r\n");
      out.write("\t\t\t\t\tvar i_no = $(\"#i_no\").val().trim();\r\n");
      out.write("\t\t\t\t\tvar em_pw = $(\"#em_pw\").val().trim();\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif(i_no==\"\"){\r\n");
      out.write("\t\t\t\t\t\talert(\"아이디를 입력해 주세요\");\r\n");
      out.write("\t\t\t\t\t\t$(\"#i_no\").focus();\r\n");
      out.write("\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t}else if(em_pw==\"\"){\r\n");
      out.write("\t\t\t\t\t\talert(\"비밀번호를 입력해 주세요\");\r\n");
      out.write("\t\t\t\t\t\t$(\"#em_pw\").focus();\r\n");
      out.write("\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\tcallLogin(i_no,em_pw);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tfunction callLogin(i_no,em_pw){\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl:\"/sm/login.uni\",\r\n");
      out.write("\t\t\t\t\ttype:\"POST\",\r\n");
      out.write("\t\t\t\t\tdata:{\r\n");
      out.write("\t\t\t\t\t\ti_no:i_no,\r\n");
      out.write("\t\t\t\t\t\tem_pw:em_pw\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\t\t\tif(data.indexOf(\"않습니다\")>-1){\r\n");
      out.write("\t\t\t\t\t\t\talert(data);\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#i_no\").val(i_no);\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#em_pw\").val(\"\").focus();\r\n");
      out.write("\t\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\tlocation.href=\"/main/goMain.uni\";\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\terror:function(request,status,error){\r\n");
      out.write("\t\t\t\t\t\talert(\"에러 났습니다 >> : \" + request.status + \" error = \" + error);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t</script>\t\t\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<div style=\"position:relative; left:0px; top:0px; width:100%; height:100%;\">\r\n");
      out.write("\t\t\t<div class=\"uniform_login\">\r\n");
      out.write("\t\t\t<h1 class=\"logo\"><img src=\"/cssExample/img/uniform_logo.png\"  width=\"460px\" alt=\"유니폼 로고\" /></h1>\t\t\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<div class=\"entry_ipt\">\r\n");
      out.write("\t\t\t\t<div class=\"user_id\">\r\n");
      out.write("\t\t\t\t\t<label for=\"i_no\"><img src=\"/cssExample/img/btn/txt_userid.jpg\"  width=\"70\" height=\"20\" alt=\"아이디\" /></label>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" id=\"i_no\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"user_pwd\">\r\n");
      out.write("\t\t\t\t\t<label for=\"em_pw\"><img src=\"/cssExample/img/btn/txt_userpwd.jpg\"  width=\"85\" height=\"20\" alt=\"비밀번호\" /></label>\r\n");
      out.write("\t\t\t\t\t<input type=\"password\" id=\"em_pw\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"btn_align\">\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" class=\"login_btn\" id=\"login_btn\" value=\"로그인\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<p class=\"txt01\"></p>\r\n");
      out.write("\t\t\t</div> <!-- //.entry_ipt -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"txt_notice\">\r\n");
      out.write("\t\t\t\t<p style=\"margin-top:50px; border-top:1px solid #dadada;\"></p>\r\n");
      out.write("\t\t\t\t<h2>꼭 확인하세요!</h2>\r\n");
      out.write("\t\t\t\t<p class=\"txt_02\">\r\n");
      out.write("\t\t\t\t\t계정정보 분실시 uni-master@uniform.co.kr 로 문의 바랍니다.<br />\r\n");
      out.write("\t\t\t\t\t(비밀번호 변경은 로그인 후 <strong>마이페이지</strong>에서 가능)\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t$(\".entry_ipt input\").focus(function(){\r\n");
      out.write("\t\t\t\t\t$(this).parent().find(\"label\").hide();\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t$(\".entry_ipt input\").blur(function(){\r\n");
      out.write("\t\t\t\t\tvar this_val = this.defaultValue;\r\n");
      out.write("\t\t\t\t\tvar new_val = $(this).val();\r\n");
      out.write("\t\t\t\t\tif(new_val == this_val || new_val.length < 1){\r\n");
      out.write("\t\t\t\t\t$(this).parent().find(\"label\").show();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t</script>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</div> <!-- //.uniform_login -->\r\n");
      out.write("\t\t</div> <!-- //end of style -->\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
